### PR TITLE
fix(menu): iconOnly does not overlap big icons

### LINKED ISSUE #409: Larger MenuItem icons overlap when using iconOnly prop
### Steps
Create a Menu with a few iconOnly huge/massive MenuItems  

```tsx
const items = [
  { key: 'home', icon: {name: 'home', size:'huge' } },
  { key: 'users', icon: {name: 'users', size: 'huge' } },
  { key: 'search', icon: {name: 'search', size: 'huge'} },
]

const MenuExampleIconOnly = () => <Menu iconOnly defaultActiveIndex={0} items={items} />
```

### Expected Result
Icons should not overlap. For example, if iconOnly is ***not*** used:
image

### Actual Result
image

### Version
0.10.0

### PR DESCRIPTION
**Pull request by bmdalex**
# fix(menu): iconOnly does not overlap big icons

Fixes #409

## Before fix:
screenshot 2018-11-16 at 15 03 04

## After fix:
screenshot 2018-11-16 at 15 22 25

### CODE REVIEW

**Comment by bmdalex** [comment]
@miroslavstastny can you take a look?

**Review by miroslavstastny — COMMENTED** [review]
From-keyboard-focus-ring moves the icon:
menuicononlyfocus

**Comment by bmdalex** [comment]
@miroslavstastny 
nice catch... damn we need these E2E tests, will try come up with a better fix

**Comment by bmdalex** [comment]
Blocked by change of priorities; will resume working in upcoming days

**Comment by bmdalex** [comment]
@miroslavstastny pls take another look, issue with key nav focus outline is fixed:

icons
icon-sizes

**Review by alinais — APPROVED** [review]
Looks good to me.

**Review by miroslavstastny — APPROVED** [review]

File: src/themes/teams/components/Menu/menuItemStyles.ts [hunk 1]
```diff
@@ -194,16 +206,16 @@ const menuItemStyles: ComponentSlotStylesInput<MenuItemPropsAndState, MenuVariab
...
+      ...(((pointing && vertical) || iconOnly) && { border: '1px solid transparent' }),
+
       ...(underlined
         ? { padding: `${pxToRem(4)} 0` }
         : pointing && vertical
           ? { padding: `${pxToRem(8)} ${pxToRem(18)}` }
           : { padding: `${pxToRem(14)} ${pxToRem(18)}` }),
 
       ...(iconOnly && {
-        width: v.iconsMenuItemSize,
```
Comment (kuzhelov) [inline src/themes/teams/components/Menu/menuItemStyles.ts:204]: 👍

**Review by kuzhelov — APPROVED** [review]
