### PR TITLE
fix(styles): update definition of `FontFace` and rename `FontFaceStyle`

### LINKED ISSUE #1454: Not possible to define fontFace with local()
## Bug Report

I am trying to define `@font-face` with `local()`:

```css
  @font-face { 
    font-family: MyHelvetica; 
    src: local("Helvetica Neue Bold"), local("HelveticaNeue-Bold"),
        url(MgOpenModernaBold.ttf);
    font-weight: bold; 
  } 
```

It will not be properly handled if I will try to use `paths` and will cause infinite loop:

```js
{
  name: "Segoe UI Local",
  paths: [
     'Segoe UI Light',
     'SegoeUI-Light',
     'Segoe WP Light',
   ],
}
```

The infinite loop will be caused because Fela in `renderer.renderFont()` expects `files`:
> It must have one of the following file extensions: .woff, .woff2, .eof, .ttf or .svg

#### Workaround

We are passing `font.style` in `this.topLevelFelaRenderer.renderFont(font.name, font.paths, font.style)` so I can do this:

```jsx
  {
    name: "Segoe UI Local",
    paths: [],
    style: {
      localAlias: [
        'Segoe UI Light',
        'SegoeUI-Light',
        'Segoe WP Light',
      ],
    }
  },
```

However, it will cause TS error `Error:(8, 7) TS2322: Type 'string[]' is not assignable to type 'string'.` because we expect plain strings in `style`.

### Solution

Expose `localAliases` in `FontFace` type and pass it down Fela renderer.

### Version
0.32.0

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1454.

# BREAKING CHANGES

Our `FontFace` definition haven't matched Fela [`renderFont()`](http://fela.js.org/docs/api/fela/Renderer.html#renderfont):

```js
{ name: "Segoe UI Local", style: {} },
// vs
{ name: "Segoe UI Local", props: {} },
```

So when are passing `localAlias` it looks that we are passing it to `style` what it is completely weird:

```js
{ name: "Segoe UI Local", style: { localAlias: 'Segoe UI' } },
```

## Migration

This PR contains:
- rename of `FontFaceStyle` to `FontFaceProps`
- rename of `style` to `props` on `FontFace` type

```diff
-import { FontFaceStyle } from '@stardust-ui/react'
+import { FontFaceProps } from '@stardust-ui/react'
```

```diff
const fontFaces: FontFaces = [
  {
    name: 'Segoe UI',
    paths: [],
-   style: { fontWeight: 400 },
+   props: { fontWeight: 400 },
  },
]
```

### CODE REVIEW

File: packages/react/src/themes/types.ts [hunk 1]
```diff
@@ -558,6 +558,7 @@ export interface FontFaceStyle {
 
 export interface FontFace {
   name: string
+  localAliases?: []
```
Comment (layershifter) [inline packages/react/src/themes/types.ts]: Fela uses `localAlias`, should I use it?

**Review by miroslavstastny — APPROVED** [review]

**Review by bmdalex — APPROVED** [review]

File: packages/react/src/themes/types.ts [hunk 2]
```diff
@@ -547,19 +547,19 @@ export interface Renderer extends FelaRenderer {}
...
 // ========================================================
 
-export interface FontFaceStyle {
+export interface FontFaceProps {
   fontStretch?: string
   fontStyle?: string
   fontVariant?: string
   fontWeight?: number
-  localAlias?: string
+  localAlias?: string | string[]
```
Comment (layershifter) [inline packages/react/src/themes/types.ts:555]: According to Fela definitions: `localAlias?: string | Array<string>`
