### PR TITLE
chore(mixed): fix imports and introduce bundler test

### LINKED ISSUE #547: Impossible to build project with Parcel or Rollup
## Bug Report

The same problem as in #497.

### Steps

1. Prepare project

```bash
git clone https://github.com/rollup/rollup-starter-app
cd rollup-starter-app
yarn
yarn add @stardust-ui/react react react-dom
yarn dev
```

2. Paste code

```js
import React from "react";
import ReactDOM from "react-dom";
import { Button, Provider, themes } from "@stardust-ui/react";

ReactDOM.render(
  React.createElement(
    Provider,
    { theme: themes.teams },
    React.createElement(Button, {
      content: "Theming",
      icon: "arrow right",
      iconPosition: "after",
      primary: true
    })
  ),
  document.getElementById("root")
);

```

### Expected Result

Everything works.

### Actual Result

image

### Version
0.13.0

### PR DESCRIPTION
**Pull request by layershifter**
This PR:
- adds a test for Rollup bundler
- cleanups imports to avoid circular issues
- fixes #547 

---

I also tested a build with Parcel manually, it works like a charm ⭐️

### CODE REVIEW

File: build/gulp/tasks/test-projects.tsx [hunk 1]
```diff
@@ -15,12 +15,13 @@ const log = msg => {
...
+export const createPackageFilename = () => tmp.tmpNameSync({ prefix: 'stardust-', postfix: '.tgz' })
 
-const buildAndPackStardust = async (): Promise<string> => {
-  await sh('yarn build:dist')
+export const runIn = path => cmd => sh(`cd ${path} && ${cmd}`)
 
-  return (await sh(`npm pack`, true)).trim()
+export const buildAndPackStardust = async (packageFilename: string) => {
+  await sh('yarn build:dist')
+  await sh(`yarn pack --filename ${packageFilename}`)
```
Comment (layershifter) [inline build/gulp/tasks/test-projects.tsx:26]: I decided to use `yarn pack` instead of NPM's. We also passing own name, this allows to generate random names and avoid caching locally.

File: types/classnames/index.d.ts [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+  interface ClassArray extends Array<ClassValue> {}
+
+  interface ClassNamesFn {
+    (...classes: ClassValue[]): string
+  }
+
+  const classNames: ClassNamesFn
+
+  export default classNames
+}
```
Comment (layershifter) [inline types/classnames/index.d.ts:20]: We decided to use custom typings for this module.

File: src/lib/colorUtils.ts [hunk 3]
```diff
@@ -1,4 +1,5 @@
-import * as Color from 'color'
+// @ts-ignore
+import Color from 'color'
```
Comment (layershifter) [inline src/lib/colorUtils.ts]: This module has the same issue as `classnames` :(

We need to make a decision about this.

File: src/components/Avatar/Avatar.tsx [hunk 4]
```diff
@@ -1,6 +1,8 @@
 import * as PropTypes from 'prop-types'
 import * as React from 'react'
-import { Image, Label, Status } from '../../'
+import Image from '../Image/Image'
+import Label from '../Label/Label'
+import Status from '../Status/Status'
```
Comment (layershifter) [inline src/components/Avatar/Avatar.tsx:5]: This change allows to avoid circular imports.

File: build/gulp/tasks/test-bundlers.tsx [hunk 5]
```diff
@@ -0,0 +1,178 @@
...
+          "createRef",
+          "PureComponent",
+          "Fragment",
+          "Children",
+          "createElement",
+          "isValidElement"
+        ],
+        "node_modules/react-dom/index.js": ["createPortal", "findDOMNode"],
+        "node_modules/react-is/index.js": ["isForwardRef"],
+        "node_modules/what-input/dist/what-input.js": ["ask"]
```
Comment (layershifter) [inline build/gulp/tasks/test-bundlers.tsx]: https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports

---

Rollup works badly with CJS modules, this config looks very 💩

File: package.json [hunk 6]
```diff
@@ -13,7 +13,7 @@
   "scripts": {
     "build": "gulp build",
     "build:docs": "gulp --series dll build:docs",
-    "build:dist": "gulp --series dll build:dist",
+    "build:dist": "gulp --series build:dist",
```
Comment (layershifter) [inline package.json:16]: We don't need `dll` in this task, this change will save some time for us 👍

File: package.json [hunk 7]
```diff
@@ -113,7 +114,7 @@
     "gulp-rename": "^1.3.0",
     "gulp-replace": "^1.0.0",
     "gulp-transform": "^3.0.5",
-    "gulp-typescript": "^5.0.0-alpha.1",
+    "gulp-typescript": "^5.0.0",
```
Comment (layershifter) [inline package.json:116]: This is stable now 👍

File: CHANGELOG.md [hunk 8]
```diff
@@ -26,6 +26,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 - The border color of the Icon is inherited if no value is provided for the `color` and `borderColor` variables @mnajdova ([#569](https://github.com/stardust-ui/react/pull/569))
 - Do not focus `Popup`'s trigger on outside click @sophieH29 ([#578](https://github.com/stardust-ui/react/pull/578))
 - Add `https` protocol to all urls used in the scripts and stylesheets in index.ejs @mnajdova ([#571](https://github.com/stardust-ui/react/pull/571))
+- Fix issue with bundling packagewith Rollup and Parcel @layershifter ([#570](https://github.com/stardust-ui/react/pull/570))
```
Comment (miroslavstastny) [inline CHANGELOG.md]: packagewith - missing space :-)

File: build/gulp/scaffold/rollup.config.js [hunk 9]
```diff
@@ -0,0 +1,110 @@
+import replace from 'rollup-plugin-replace'
+import resolve from 'rollup-plugin-node-resolve'
+import commonjs from 'rollup-plugin-commonjs'
+
+const lodashExports = [
```
Comment (miroslavstastny) [inline build/gulp/scaffold/rollup.config.js]:
```
(!) Missing exports
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
node_modules/@stardust-ui/react/dist/es/components/Dropdown/Dropdown.js
pickBy is not exported by node_modules/lodash/lodash.js
```

How is this going to scale? Whenever a new function is used, do I need to remember I have to add it here?

File: build/gulp/tasks/test-projects.tsx (hunk 1 above)
Comment (miroslavstastny) [reply build/gulp/tasks/test-projects.tsx:26]: I vaguely remember @kuzhelov used `npm` for a reason...

File: build/gulp/tasks/test-bundlers.tsx [hunk 10]
```diff
@@ -0,0 +1,47 @@
...
+    path.resolve(tmpDirectory, 'app.js'),
+  )
+  fs.copyFileSync(
+    path.resolve(__dirname, '..', 'scaffold', 'rollup.config.js'),
+    path.resolve(tmpDirectory, 'rollup.config.js'),
+  )
+  logger(`✔️Source and bundler's config were created`)
+
+  await runIn(tmpDirectory)(`yarn rollup -c`)
+  logger(`✔️Example project was successfully built: ${tmpDirectory}`)
```
Comment (miroslavstastny) [inline build/gulp/tasks/test-bundlers.tsx]: It seems we are ignoring rollup warnings. Are we ok with it or would we like to use this as an opportunity to tighten our rules and require warning-free build in rollup? (no warnings are currently allowed in webpack build)

File: .circleci/config.yml [hunk 11]
```diff
@@ -58,6 +58,9 @@ jobs:
 #      - run:
```
Comment (kuzhelov) [inline .circleci/config.yml]: when we are planning to return this? And, actually, what was specific reason to disable these tests - currently we have no _any_ checks that _any_ client is able to consume our library

Comment (layershifter) [reply .circleci/config.yml]: After #550 will be merged

File: build/gulp/tasks/test-projects.tsx (hunk 1 above)
Comment (kuzhelov) [reply build/gulp/tasks/test-projects.tsx:26]: the reason for that was just to use the standard tool and not its wrapper, as it could easily entice us to use some features that are `yarn`-specific. However, we may leave it as it is at the moment, no strong opinion here, as this describes set of actions made on our side, not the client's one

File: build/gulp/scaffold/rollup.config.js (hunk 9 above)
Comment (layershifter) [reply build/gulp/scaffold/rollup.config.js]: Yes, it's a real problem 👎  `lodash` is CJS module, so the there is only one option.
If we will use Babel and `babel-plugin-lodash` this problem will gone.

File: build/gulp/scaffold/rollup.config.js [hunk 12]
```diff
@@ -0,0 +1,110 @@
+import replace from 'rollup-plugin-replace'
```
Comment (kuzhelov) [inline build/gulp/scaffold/rollup.config.js]: this should be placed somewhere under `test-projects` at the very least (we should create corresponding dir) - so that this client-oriented tests functionality will be cohesively structured

File: .circleci/config.yml [hunk 13]
```diff
@@ -58,6 +58,9 @@ jobs:
...
 #          name: Project Tests
 #          command: yarn test:projects:cra-ts
+      - run:
+          name: Bundler Tests
+          command: yarn test:bundlers:rollup
```
Comment (kuzhelov) [inline .circleci/config.yml]: would suggest `test:projects:rollup` - as this won't introduce additional entropy and will still suggest that stack that client is using for her project

File: build/gulp/scaffold/rollup.config.js (hunk 12 above)
Comment (layershifter) [reply build/gulp/scaffold/rollup.config.js]: It's already placed in the separate dir. I don't want to be so specific for now.

File: .circleci/config.yml (hunk 13 above)
Comment (layershifter) [reply .circleci/config.yml]: Moved into single entry, `yarn test:projects` 👍

File: build/gulp/scaffold/rollup.config.js (hunk 9 above)
Comment (layershifter) [reply build/gulp/scaffold/rollup.config.js]: Resolved with `external` and `output.globals`, now is much cleaner

File: build/gulp/tasks/test-bundlers.tsx (hunk 10 above)
Comment (layershifter) [reply build/gulp/tasks/test-bundlers.tsx]: I reworked it, now we have a warning whitelist, other warnings will throw.

We can fix all left circular imports in a separate PR because it will require more work.

File: build/gulp/tasks/test-projects.tsx (hunk 1 above)
Comment (layershifter) [reply build/gulp/tasks/test-projects.tsx:26]: It looks more cleaner than `(await sh(`npm pack`, true)).trim()`, so I will left `yarn pack` there.

File: src/lib/colorUtils.ts (hunk 3 above)
Comment (layershifter) [reply src/lib/colorUtils.ts]: Done, this package was removed from dependencies

File: build/gulp/scaffold/rollup.config.js (hunk 12 above)
Comment (kuzhelov) [reply build/gulp/scaffold/rollup.config.js]: yes, but the same reasoning would apply well in case it will be put in _any_ dir - thus, I am not sure that this is a valid argument. 

The reasoning behind my ask is the following: currently, with the dir introduced at the place where you are suggesting, we would have the following project structure:

```
/build/gulp
  /scaffold
  /tasks
       /test-projects
```

So, reasonable question is why `scaffold` directory is placed at this level of folder hierarchy? Is its content shared by any agents/tasks? The answer is "no" - the only place where it is used is `test-projects` module. Thus, I would suggest to put these bits to the module those belong to at the moment.

File: .circleci/config.yml [hunk 14]
```diff
@@ -55,9 +55,9 @@ jobs:
       - run:
           name: Visual Tests
           command: yarn test:visual
-#      - run:
-#          name: Project Tests
-#          command: yarn test:projects:cra-ts
+      - run:
+          name: Project Tests
+          command: yarn test:projects
```
Comment (kuzhelov) [inline .circleci/config.yml:60]: 👍

File: build/gulp/tasks/test-projects.tsx [hunk 15]
```diff
@@ -120,6 +125,54 @@ export default App;
...
+  )
+  logger(`✔️Source and bundler's config were created`)
+
+  await runIn(tmpDirectory)(`yarn rollup -c`)
+  logger(`✔️Example project was successfully built: ${tmpDirectory}`)
+})
+
+task(
+  'test:projects',
+  series(
```
Comment (kuzhelov) [inline build/gulp/tasks/test-projects.tsx:169]: actually, can we run them in parallel? It seems that there is no shared state between these tasks

Comment (layershifter) [reply build/gulp/tasks/test-projects.tsx:169]: I will left it as is for now. When this task will be enabled, we will able to test that it works in parallel. However, I almost sure that it will work.

File: build/gulp/scaffold/rollup.config.js (hunk 12 above)
Comment (layershifter) [reply build/gulp/scaffold/rollup.config.js]: > Is its content shared by any agents/tasks? The answer is "no" - the only place where it is used is test-projects module.

At now, yes. But in the future, I think that we will have other tasks that will should also have files and templates.

Comment (mnajdova) [reply build/gulp/scaffold/rollup.config.js]: I must agree here that better directory structure would reflect exactly what we test even. Having structure, something like:
```
/build/gulp
  /tasks
       /test-projects
         /cra-ts
         /parcel
         ...
```
will be much more cleaner, and it will be obvious what scenarios we got covered so far...

Comment (layershifter) [reply build/gulp/scaffold/rollup.config.js]: @kuzhelov @mnajdova you convinced me and I made these changes 👍

**Review by kuzhelov — APPROVED** [review]
