### PR TITLE
fix(Animation): not to throw if children is not set

### LINKED ISSUE #2341: Animation with no children throws
### Steps
```
<Animation />
```

### Expected Result
Renders empty animation.

### Actual Result
Cannot read property 'className' of undefined 💣

### Version
0.44.0 (works as expected in 0.43.2)

### Testcase
https://codesandbox.io/s/fluent-ui-example-cihqy

### PR DESCRIPTION
**Pull request by mnajdova**
Fixes https://github.com/microsoft/fluent-ui-react/issues/2341

### CODE REVIEW

**Review by miroslavstastny — COMMENTED** [review]
no UT?

File: packages/react/test/specs/components/Animation/Animation-test.tsx [hunk 1]
```diff
@@ -2,11 +2,22 @@ import * as React from 'react'
...
     handlesAsProp: false,
   })
+
+  test('does not throw if children is not passed', () => {
+    consoleUtil.disableOnce()
+    // @ts-ignore
+    expect(() => mountWithProvider(<Animation />)).not.toThrowError()
+
+    consoleUtil.disableOnce()
+    // @ts-ignore
```
Comment (layershifter) [inline packages/react/test/specs/components/Animation/Animation-test.tsx]: Ouch, why? 😭

Comment (mnajdova) [reply packages/react/test/specs/components/Animation/Animation-test.tsx]: We are testing that, if user passes undefined as children it will not throw. On the other hand the typings are not allowing undefined as children, so we must use ts-ignore (feels awkward, but I don't have a better idea of how to test it...)

Comment (mnajdova) [reply packages/react/test/specs/components/Animation/Animation-test.tsx]: @miroslavstastny any better idea?

Comment (miroslavstastny) [reply packages/react/test/specs/components/Animation/Animation-test.tsx]: no

**Review by layershifter — APPROVED** [review]
