### PR TITLE
fix(popper): flickering

### LINKED ISSUE #1361: Inline popup cause wrong popup rendering
### Steps
use popup inline prop 

### Expected Result
popup is rendered next to element

### Actual Result
popup is rendered in some space under element 

### Version
0.30.0

inline_popup

Code used in example: 

```jsx
import * as React from 'react'
import keyboardKey from 'keyboard-key'
import { Popup, Menu, Reaction, ReactionProps, popupAutoFocusBehavior, Avatar, Chat } from '@stardust-ui/react'

const getAriaLabel = ({ content: numberOfPersons, icon: emojiType }: ReactionProps) => {
  if (numberOfPersons === 1) {
    return `One person reacted to this message with a ${emojiType} emoji. Open menu to see person who reacted.`
  }
  return `${numberOfPersons} people reacted this message with a ${emojiType} emoji. Open menu to see people who reacted.`
}

class ReactionPopup extends React.Component<ReactionProps, any> {
  state = {
    open: false,
  }

  handleKeyDownOnMenu = e => {
    if ((e.shiftKey && e.keyCode === keyboardKey.Tab) || e.keyCode === keyboardKey.Tab) {
      this.setState({ open: false })
    }
  }

  handleOpenChange = (e, { open }) => {
    this.setState({ open })
  }

  render() {
    return (
      <Popup
        trigger={
          <Reaction
            as="button"
            aria-haspopup="true"
            {...this.props}
            aria-label={getAriaLabel(this.props)}
          />
        }
        content={{
          content: (
            <Menu
              items={['Jane Doe', 'John Doe']}
              vertical
              variables={{ borderColor: 'transparent' }}
              onKeyDown={this.handleKeyDownOnMenu}
            />
          ),
        }}
        inline
        on="hover"
        open={this.state.open}
        onOpenChange={this.handleOpenChange}
        accessibility={popupAutoFocusBehavior}
      />
    )
  }
}

const reactions = [
  {
    icon: "thumbs up",
    content: "1K",
    key: "likes",
    variables: { meReacting: true }
  },
  { icon: "thumbs down", content: 2, key: "dislikes" }
];

const reactionsWithPopup = reactions.map(reaction => render =>
  render(reaction, (Component, props) => <ReactionPopup {...props} />)
);

const actionMenu = {
  iconOnly: true,
  items: [
    { key: "like", icon: "like", title: "Like" },
    { key: "more", icon: "more", title: "More actions" }
  ]
};

const items = [
  {
    attached: "top",
    contentPosition: "end",
    message: {
      content: (
        <Chat.Message
          reactionGroup={{
            items: reactionsWithPopup
          }}
          actionMenu={actionMenu}
          content="Hello"
          author="John Doe"
          timestamp="Yesterday, 10:15 PM"
          mine
        />
      )
    },
    key: "message-1"
  },
  {
    attached: "bottom",
    contentPosition: "end",
    key: "message-2",
    message: {
      content: (
        <Chat.Message
          reactionGroup={{ items: reactionsWithPopup }}
          actionMenu={actionMenu}
          reactionGroupPosition={"end"}
          content="I'm back!"
          author="John Doe"
          timestamp="Yesterday, 10:15 PM"
          mine
        />
      )
    }
  },
  {
    gutter: {
      content: <Avatar image="public/images/avatar/small/ade.jpg" />
    },
    message: {
      content: (
        <Chat.Message
          reactionGroup={{
            items: reactionsWithPopup
          }}
          actionMenu={actionMenu}
          content="Hi"
          author="Jane Doe"
          timestamp="Yesterday, 10:15 PM"
        />
      )
    },
    key: "message-3"
  }
];

const MessageReactionsWithPopup = () => <Chat items={items} />;

const Example = () => <MessageReactionsWithPopup  />

export default Example
```

### LINKED ISSUE #1415: Popup content jumps for a split second when opening
### Steps
- build master
- go to `Popup` examples page: http://localhost:8080/components/popup#types-popup
- click the button to open the `Popup`

### Expected Result
Popup opens without jump

### Actual Result
Popup has a small but noticeable jump when opening (see gif below) 💣

popup

### Version
UNRELEASED

### PR DESCRIPTION
**Pull request by bmdalex**
## fix(popper): flickering

Fixes #1415
Fixes #1361 

#### Popup content jumps for a split second when opening.
Perform the following steps to reproduce the problem:
- build master
- go to `Popup` examples page: http://localhost:8080/components/popup#types-popup
- click the button to open the `Popup`

#### Expected Result
Popup opens without jump

#### Actual Result
Popup has a small but noticeable jump when opening (see gif below) 💣

popup

### Proposed fix

Create the `PopperJS` instance earlier, aka immediately after we get a `ref` to the `children` prop that the `popper.js` box is going to display:

```jsx
<Ref
  innerRef={contentElement => {
    contentRef.current = contentElement
    createInstance() // create `PopperJS` instance here !! 
  }}
>
  {child as React.ReactElement}
</Ref>
```

### CODE REVIEW

File: packages/react/src/lib/positioner/types.ts [hunk 1]
```diff
@@ -66,7 +67,7 @@ export interface PopperProps extends PositioningProps {
   /**
    * Ref object containing the target node (the element that we're using as reference for Popper box).
    */
-  targetRef?: React.RefObject<Element>
+  targetRef: React.RefObject<Element>
```
Comment (bmdalex) [inline packages/react/src/lib/positioner/types.ts:70]: `Popper` won't work without providing this, I think it makes sense to mark it as required

File: packages/react/src/lib/positioner/Popper.tsx [hunk 2]
```diff
@@ -92,39 +123,49 @@ const Popper: React.FunctionComponent<PopperProps> = props => {
...
+          scheduleUpdate,
         })
       : React.Children.only(children)
 
-  return <Ref innerRef={contentRef}>{child as React.ReactElement}</Ref>
+  return (
+    <Ref
+      innerRef={contentElement => {
+        contentRef.current = contentElement
+        createInstance()
```
Comment (bmdalex) [inline packages/react/src/lib/positioner/Popper.tsx:149]: This is critical. Thinking to add a comment here to stress on that..

File: packages/react/src/lib/positioner/Popper.tsx [hunk 3]
```diff
@@ -37,10 +37,8 @@ const Popper: React.FunctionComponent<PopperProps> = props => {
 
   const popperRef = React.useRef<PopperJS>()
   const contentRef = React.useRef<HTMLElement>(null)
-  const latestPlacement = React.useRef<PopperJS.Placement>(proposedPlacement)
-  const [computedPlacement, setComputedPlacement] = React.useState<PopperJS.Placement>(
-    proposedPlacement,
-  )
+  const latestPlacement = React.useRef<PopperJS.Placement>()
```
Comment (kuzhelov) [inline packages/react/src/lib/positioner/Popper.tsx]: where this guy is used? highly likely we should remove it now

Comment (bmdalex) [reply packages/react/src/lib/positioner/Popper.tsx]: line 118, not in the scope of the PR

File: packages/react/src/lib/positioner/Popper.tsx (hunk 2 above)
Comment (bmdalex) [reply packages/react/src/lib/positioner/Popper.tsx:149]: done

File: packages/react/src/lib/positioner/Popper.tsx [hunk 4]
```diff
@@ -51,8 +49,41 @@ const Popper: React.FunctionComponent<PopperProps> = props => {
...
   )
 
-  React.useEffect(
+  const scheduleUpdate = React.useCallback(
+    () => {
+      if (popperRef.current) {
+        popperRef.current.scheduleUpdate()
+      }
+    },
+    [popperRef.current],
```
Comment (layershifter) [inline packages/react/src/lib/positioner/Popper.tsx]: This dependency is not required because `popperRef` will be the same object across multiple renders

https://overreacted.io/how-are-function-components-different-from-classes/

File: packages/react/src/lib/positioner/Popper.tsx [hunk 5]
```diff
@@ -51,8 +49,41 @@ const Popper: React.FunctionComponent<PopperProps> = props => {
...
+  )
+
+  const destroyInstance = React.useCallback(
+    () => {
+      if (popperRef.current) {
+        popperRef.current.destroy()
+        popperRef.current = null
+      }
+    },
+    [popperRef.current],
```
Comment (layershifter) [inline packages/react/src/lib/positioner/Popper.tsx]: Same thing ⬆️

File: packages/react/src/lib/positioner/Popper.tsx [hunk 6]
```diff
@@ -37,10 +37,8 @@ const Popper: React.FunctionComponent<PopperProps> = props => {
 
   const popperRef = React.useRef<PopperJS>()
   const contentRef = React.useRef<HTMLElement>(null)
-  const latestPlacement = React.useRef<PopperJS.Placement>(proposedPlacement)
-  const [computedPlacement, setComputedPlacement] = React.useState<PopperJS.Placement>(
-    proposedPlacement,
-  )
+  const latestPlacement = React.useRef<PopperJS.Placement>()
+  const [computedPlacement, setComputedPlacement] = React.useState<PopperJS.Placement>()
```
Comment (layershifter) [inline packages/react/src/lib/positioner/Popper.tsx]: Is it correct that we don't have initial value there more?

File: packages/react/src/lib/positioner/Popper.tsx [hunk 7]
```diff
@@ -51,8 +49,41 @@ const Popper: React.FunctionComponent<PopperProps> = props => {
...
+    computedModifiers,
+    enabled,
+    userModifiers,
+    positionFixed,
+    proposedPlacement,
+  ]
+
+  const createInstance = React.useCallback(
     () => {
+      destroyInstance()
```
Comment (layershifter) [inline packages/react/src/lib/positioner/Popper.tsx]: Can we use there `useEffect()` behavior:

```js
const createInstance = React.useCallback(
  () => {
    // logic

   return () => destroyInstance()
  }

File: packages/react/src/lib/positioner/Popper.tsx [hunk 8]
```diff
@@ -92,39 +123,50 @@ const Popper: React.FunctionComponent<PopperProps> = props => {
...
         modifiers,
         onCreate: handleUpdate,
         onUpdate: handleUpdate,
       }
 
       popperRef.current = createPopper(targetRef.current, contentRef.current, options)
-      return () => popperRef.current.destroy()
     },
-    [computedModifiers, eventsEnabled, userModifiers, positionFixed, proposedPlacement],
+    [targetRef.current, contentRef.current, ...instanceDependencies],
```
Comment (layershifter) [inline packages/react/src/lib/positioner/Popper.tsx]: `targetRef.current`, `contentRef.current` are not dependencies of this function because it relies of `*Ref`s

File: packages/react/src/lib/positioner/Popper.tsx (hunk 6 above)
Comment (bmdalex) [reply packages/react/src/lib/positioner/Popper.tsx]: looks like we don't need it, but I reverted for consistency, no harm there

File: packages/react/src/lib/positioner/Popper.tsx (hunk 5 above)
Comment (bmdalex) [reply packages/react/src/lib/positioner/Popper.tsx]: addressed, thanks

File: packages/react/src/lib/positioner/Popper.tsx (hunk 8 above)
Comment (bmdalex) [reply packages/react/src/lib/positioner/Popper.tsx]: addressed, thanks

File: packages/react/src/lib/positioner/Popper.tsx (hunk 4 above)
Comment (bmdalex) [reply packages/react/src/lib/positioner/Popper.tsx]: addressed, thanks

**Review by layershifter — APPROVED** [review]

File: packages/react/src/components/Menu/MenuItem.tsx [hunk 9]
```diff
@@ -247,7 +247,6 @@ class MenuItem extends AutoControlledComponent<WithAsProp<MenuItemProps>, MenuIt
               align={vertical ? 'top' : 'start'}
               position={vertical ? 'after' : 'below'}
               targetRef={this.itemRef}
-              modifiers={{ flip: { flipVariationsByContent: true } }}
```
Comment (kuzhelov) [inline packages/react/src/components/Menu/MenuItem.tsx:250]: removed as this modifier is applied by default now

**Review by kuzhelov — APPROVED** [review]
