### PR TITLE
fix(Alert): add `isFromKeyboard` to state

### LINKED ISSUE #1230: Unable to style action button in Alert component
### Steps
I am unable to add focus styles to the Alert action button, because `isFromKeyboard` is not recognized

### Extra info
@jurokapsiar: The problem is that `isFromKeyboard` is not in the state of `Alert`, it is in the state of `Button`. How can she style the button based on its state? Do we need to add the state to Alert or is there a better way?

Sounds like we need to add `isFromKeyboard` to the state to be able to detect and style appropriately.

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1230.

### CODE REVIEW

File: packages/react/src/components/Alert/Alert.tsx [hunk 1]
```diff
@@ -108,6 +130,7 @@ class Alert extends UIComponent<ReactProps<AlertProps>> {
     return (
       <ElementType
         className={classes.root}
+        onFocus={this.handleFocus}
```
Comment (mnajdova) [inline packages/react/src/components/Alert/Alert.tsx:133]: Shouldn't this be added on the action, instead of the root element?

Comment (mnajdova) [reply packages/react/src/components/Alert/Alert.tsx:133]: The Alert itself as far as I understand is not focusable

**Review by codepretty — APPROVED** [review]
Yay! Thanks so much for fixing this! :)

File: packages/react/src/components/Alert/Alert.tsx (hunk 1 above)
Comment (layershifter) [reply packages/react/src/components/Alert/Alert.tsx:133]: Current points:
- as I see the whole `Alert` is not focusable by [spec](https://www.w3.org/TR/wai-aria-practices/examples/alert/alert.html), so currently only `action` slot can be focused
- `focus` event will be propogated from the `action` slot

If we will have issues with this in future, i.e. the whole `Alert` can be focused we can separate values to `isFromKeyboard` & `isAlertFromKeyboard`.

Comment (mnajdova) [reply packages/react/src/components/Alert/Alert.tsx:133]: Make sense, I understand that it will be propagated, but my point was more in a sense that, if the content of the alert has focusable event, it would in the same way behave. But we can anyway use the `':focus'` selector together with the `isFromKeyboard` state value, so it should be ok.

**Review by mnajdova — APPROVED** [review]
