### PR TITLE
fix(unit tests): fix warnings

### LINKED ISSUE #1058: Unit tests report warnings
### Steps
```bash
yarn test
```

### Expected Result
No warnings

### Actual Result
```log
message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
...
(node:88888) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:88888) UnhandledPromiseRejectionWarning: TypeError: document.createRange is not a function
```

### Version
0.23.1

### PR DESCRIPTION
**Pull request by miroslavstastny**
Fixes #1058:
- esInterop warnings
- popper warnings
- it is now possible to run tests from WebStorm

### CODE REVIEW

File: packages/react/src/themes/teams/components/Icon/svg/icons/numberList.tsx [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import * as React from 'react'
 import cx from 'classnames'
 import { teamsIconClassNames } from '../teamsIconClassNames'
-import { TeamsSvgIconSpec } from 'src/themes/teams/components/Icon/svg/types'
+import { TeamsSvgIconSpec } from '../../svg/types'
```
Comment (layershifter) [inline packages/react/src/themes/teams/components/Icon/svg/icons/numberList.tsx:4]: Fixed path 🚗

File: build/jest/jest.config.common.js [hunk 2]
```diff
@@ -1,12 +1,16 @@
 const { jest: lernaAliases } = require('lerna-alias')
 
+const setupTestFrameworkScriptFile = process.env.CI
+  ? `${__dirname}/setup.strict.ts`
+  : `${__dirname}/setup.common.ts`
+
```
Comment (layershifter) [inline build/jest/jest.config.common.js:6]: Moved all to a single config

File: jest.config.js [hunk 3]
```diff
@@ -1,3 +1,10 @@
...
+const { rollup: lernaAlises } = require('lerna-alias')
 
-module.exports = commonConfig
+// packages/react/src -> packages/react,
+// as lernaAliases append 'src' by default
+const stardustPackages = lernaAlises({ sourceDirectory: false })
+const projects = Object.keys(stardustPackages).map(packageName => stardustPackages[packageName])
+
+module.exports = {
+  projects,
```
Comment (layershifter) [inline jest.config.js:9]: Reused [`projects`](https://jestjs.io/docs/en/configuration#projects-array-string-projectconfig) feature, now we can have different configs for each package ✋

File: .circleci/config.yml [hunk 4]
```diff
@@ -53,7 +53,7 @@ jobs:
           command: yarn prettier
       - run:
           name: Unit Tests
-          command: yarn test --strict --maxWorkers=4
+          command: yarn test --maxWorkers=2
```
Comment (layershifter) [inline .circleci/config.yml:56]: https://discuss.circleci.com/t/babel-7-jest-results-in-timeout/25383/6

**Review by layershifter — APPROVED** [review]
👍
