### PR TITLE
fix(List): handle onClick and onFocus on items correctly

### LINKED ISSUE #680: onClick handler does not work properly for List component
### Steps
Create a List component using shorthand props for the items list. Specify an onClick handler for each item.

### Expected Result
When an item is clicked on, the onClick handler is called and the item is passed in as the second argument (as it works with menu items currently).

### Actual Result
The item is not passed to the callback

### Version
0.13.1

### Testcase
```tsx
import React from 'react'
import { List, Image } from '@stardust-ui/react'

const itemSelected = (evt, item) => {
  alert(item.index);
}

const items = [
  {
    key: 'irving',
    media: <Image src="public/images/avatar/small/matt.jpg" avatar />,
    header: 'Irving Kuhic',
    headerMedia: '7:26:56 AM',
    content: 'Program the sensor to the SAS alarm through the haptic SQL card!',
    onClick: itemSelected
  },
  {
    key: 'skyler',
    media: <Image src="public/images/avatar/small/steve.jpg" avatar />,
    header: 'Skyler Parks',
    headerMedia: '11:30:17 PM',
    content: 'Use the online FTP application to input the multi-byte application!',
    onClick: itemSelected
  },
  {
    key: 'dante',
    media: <Image src="public/images/avatar/small/nom.jpg" avatar />,
    header: 'Dante Schneider',
    headerMedia: '5:22:40 PM',
    content: 'The GB pixel is down, navigate the virtual interface!',
    onClick: itemSelected
  },
]

const selection = knobs => (knobs === undefined ? true : knobs.selection)

const ListExampleSelection = ({ knobs }) => <List selection={selection(knobs)} items={items} />

export default ListExampleSelection
```

Example that works using Menu:

```tsx
import { Menu } from '@stardust-ui/react'

const itemSelected = (evt, menuItem) => {
  alert(menuItem.index);
}

const items = [
  { key: 'editorials', content: 'Editorials', onClick: itemSelected},
  { key: 'review', content: 'Reviews', onClick: itemSelected },
  { key: 'events', content: 'Upcoming Events', onClick: itemSelected },
];

const MenuExampleUnderlinedPrimary = () => (
  <Menu defaultActiveIndex={0} items={items} underlined primary />
)

export default MenuExampleUnderlinedPrimary
```

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #680.

### CODE REVIEW

File: src/components/List/ListItem.tsx [hunk 1]
```diff
@@ -85,6 +86,7 @@ class ListItem extends UIComponent<ReactProps<ListItemProps>, ListItemState> {
     media: PropTypes.any,
 
     selectable: PropTypes.bool,
+    index: PropTypes.number,
```
Comment (layershifter) [inline src/components/List/ListItem.tsx:89]: Actually, `Menu` does the same thing

File: test/specs/components/List/List-test.tsx [hunk 2]
```diff
@@ -72,5 +72,22 @@ describe('List', () => {
...
+        <List items={getItems(onClick)} onSelectedIndexChange={onSelectedIndexChange} selectable />,
+      ).find('ListItem')
+
+      listItems
+        .first()
+        .find('li')
+        .first()
+        .simulate('click')
+
+      expect(onClick).toHaveBeenCalled()
```
Comment (miroslavstastny) [inline test/specs/components/List/List-test.tsx:89]: Don't you want to check cb params as well?

**Review by miroslavstastny — APPROVED** [review]

File: test/specs/components/List/List-test.tsx (hunk 2 above)
Comment (layershifter) [reply test/specs/components/List/List-test.tsx:89]: Done 👍
