### PR TITLE
fix(provider): fix for rendering components outside provider

### LINKED ISSUE #372: Rendering a Component outside of Provider should fail with meaningful error
### Steps
Create a new application, create a component (`<Button />`) without wrapping that by `<Provider>`.

### Expected Result
Component rendering fails with meaningful error (or warning) 

### Actual Result
Component dom renders, no styles are applied 💣

### Version
0.9.1

### PR DESCRIPTION
**Pull request by bmdalex**
# Provider

This PR is a fix proposal that closes #372.

### TODO

- [x] Update the CHANGELOG.md

## Proposed solution

Meaningful console error with link pointing to documentation where user can find examples of correct usage:
screen shot 2018-10-23 at 12 47 56

### CODE REVIEW

File: src/lib/renderComponent.tsx [hunk 1]
```diff
@@ -136,6 +152,10 @@ const renderComponent = <P extends {}>(
   return (
     <FelaTheme
       render={(theme: IThemePrepared) => {
+        if (_.isEmpty(theme) || !theme.provided) {
```
Comment (kuzhelov) [inline src/lib/renderComponent.tsx]: lets focus on the case where there is some non-empty `theme` object provided and `theme.provided` is false. When this could happen? Currently we have default team being **non-empty** object (that automatically passes `_.isEmpty` check) - and there is no need to additionally check for `provided`, as this is an equivalent of `emptyTheme` being used.

I would propose to remove `provided` prop and use just `_.isEmpty` check - this should be enough. Please, feel free to suggest the cases if I am wrong with this assumption.

File: src/lib/mergeThemes.ts [hunk 2]
```diff
@@ -184,6 +184,7 @@ const mergeThemes = (...themes: IThemeInput[]): IThemePrepared => {
     fontFaces: [],
     staticStyles: [],
     icons: {},
+    provided: true,
```
Comment (kuzhelov) [inline src/lib/mergeThemes.ts]: seems that we can avoid this property to be introduced - it would be enough just to check that `theme` object is not empty for theme context consumer

File: src/lib/renderComponent.tsx [hunk 3]
```diff
@@ -118,6 +119,21 @@ const renderWithFocusZone = (render, focusZoneDefinition, config, focusZoneRef):
...
+const getProviderNotUsedWarningElement = (displayName: string) => {
+  console.error(`Incorrect usage. Your component needs to be wrapped using the Provider component:
+
+import * as React from 'react';
+import { ${displayName}, Provider, themes } from '@stardust-ui/react';
+
+<Provider theme={themes.teams}>
+  <${displayName} />
+</Provider>
+`)
```
Comment (levithomason) [inline src/lib/renderComponent.tsx]: The error is not so much that the component is not wrapped, but that the Provider is missing.  Let's point that out and link them to the quick start docs.

File: src/lib/renderComponent.tsx [hunk 4]
```diff
@@ -118,6 +119,21 @@ const renderWithFocusZone = (render, focusZoneDefinition, config, focusZoneRef):
   return render(config)
 }
 
+const getProviderNotUsedWarningElement = (displayName: string) => {
+  console.error(`Incorrect usage. Your component needs to be wrapped using the Provider component:
```
Comment (levithomason) [inline src/lib/renderComponent.tsx]: We should probably also implement a cache check so we don't spam the console for every component on the page.

**Comment by levithomason** [comment]
@Bugaa92 Note, if you slightly adjust the PR description then this PR will automatically close the associated issue once it is merged.  See here:

https://help.github.com/articles/closing-issues-using-keywords/

File: src/lib/renderComponent.tsx (hunk 1 above)
Comment (bmdalex) [reply src/lib/renderComponent.tsx]: removed `provided` flag

File: src/lib/mergeThemes.ts (hunk 2 above)
Comment (bmdalex) [reply src/lib/mergeThemes.ts]: removed `provided` flag

File: src/lib/renderComponent.tsx (hunk 3 above)
Comment (bmdalex) [reply src/lib/renderComponent.tsx]: done

File: src/lib/renderComponent.tsx (hunk 4 above)
Comment (bmdalex) [reply src/lib/renderComponent.tsx]: done

File: src/lib/constants.ts [hunk 5]
```diff
@@ -0,0 +1,7 @@
+const docSiteUrl = 'https://stardust-ui.github.io/react'
+const quickStartUrl = `${docSiteUrl}/quick-start`
```
Comment (levithomason) [inline src/lib/constants.ts]: Let's not dupe constants that already exist in the repo.  Let's pull these from `/docs` into `/src`.  The docs are allowed to import src files.

File: src/lib/providerMissingHandler.ts [hunk 6]
```diff
@@ -0,0 +1,15 @@
+import ct from './constants'
```
Comment (levithomason) [inline src/lib/providerMissingHandler.ts]: nit: no abbrev please :)

File: src/lib/constants.ts (hunk 5 above)
Comment (bmdalex) [reply src/lib/constants.ts]: done, pulled all constants together

File: src/lib/providerMissingHandler.ts (hunk 6 above)
Comment (bmdalex) [reply src/lib/providerMissingHandler.ts]: fixed

**Comment by bmdalex** [comment]
@levithomason comments were addressed

**Review by kuzhelov — APPROVED** [review]
