### PR TITLE
 fix(Accordion|Dropdown): fix default props in auto controlled mode

### LINKED ISSUE #610: AutoControlled component does not handle NOT autocontrolled state
### Steps
Let's ```componentA``` is derived from ```AutoControlled``` component

```componentA``` has state object
```js
state = {
    someState: true
}
```

And has autocontrolled state and props

```js

props = {
...
autoControlledState: bool
defaultAutoControlledState: bool
...
}
...
static autoControlledProps = ['autoControlledState']
...
```

Steps:
1. Use component 
```js
<componentA defaultAutoControlledState={true} />
```
2. Debug component
3. Check applied state to component

### Expected Result
Expected state is 
```js
state = {
    someState: true,
    autoControlledState: true
}
```

### Actual Result
```js
state = {
    someState: true,
}
```

As a result, ```state``` of the component is not taken into account in ```AutoControlled``` component. Then constructor of ```componentA``` overrides the state value with what was set in ```AutoControlled``` component during initialization.

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #610.

### CODE REVIEW

File: src/components/Accordion/Accordion.tsx [hunk 1]
```diff
@@ -118,8 +118,6 @@ class Accordion extends AutoControlledComponent<ReactProps<AccordionProps>, any>
   static Title = AccordionTitle
   static Content = AccordionContent
 
-  state: any = { activeIndex: [0] }
-
   getInitialAutoControlledState({ exclusive }) {
     return { activeIndex: exclusive ? -1 : [-1] }
```
Comment (layershifter) [inline src/components/Accordion/Accordion.tsx:122]: This line didn't work previously, that's why we have visual regressions there.

Comment (mnajdova) [reply src/components/Accordion/Accordion.tsx:122]: To me it seems, according to the changes in screener that that line was indeed working:
image
 as the previous accepted screen has the first element inside active. Not quite sure how did you conclude that it was not working before.. Maybe I am missing something?

Comment (mnajdova) [reply src/components/Accordion/Accordion.tsx:122]: I understand that this is part of the autocontroll props and should not be initialized, but can't understand why do you say it was not working previously

**Review by mnajdova — APPROVED** [review]
