### PR TITLE
fix(docs): update Babel config in docs

### LINKED ISSUE #1073: RadioGroup Button is broken on Edge Browser
### Steps
Open https://stardust-ui.github.io/react/components/radio-group on Edge Browser

### Expected Result
The formatting should be correct and No functional error should be there

### Actual Result
image

image

### Version
0.23.1

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1073.

### CODE REVIEW

File: docs/src/components/Playground/renderConfig.ts [hunk 1]
```diff
@@ -6,6 +6,7 @@ import * as ReactDOM from 'react-dom'
 export const babelConfig = {
   plugins: [
     'proposal-class-properties',
+    'proposal-object-rest-spread',
```
Comment (layershifter) [inline docs/src/components/Playground/renderConfig.ts:9]: Edge doesn't support object spread, this plugin does required transform

**Review by bmdalex — APPROVED** [review]
