### PR TITLE
fix(lib): correctly handle arrays in felaSanitizeCssPlugin

### LINKED ISSUE #572: CSS Fallback values do not work
### Steps
```jsx
import React from 'react'
import { Menu, Provider } from '@stardust-ui/react'

const items = [
  { key: 'editorials', content: 'Editorials' },
  { key: 'review', content: 'Reviews' },
  { key: 'events', content: 'Upcoming Events' },
]

const MenuExamplePrimary = () => (
  <Provider theme={{
    componentStyles: {
      MenuItem: {
        root: {
          border: '2px solid gray',
          borderColor: ['red', 'blue'],
        }
      }
    }
  }}>
    <Menu defaultActiveIndex={0} items={items} primary />
  </Provider>
)

export default MenuExamplePrimary
```
### Expected Result
`MenuItem::a` has following styles:
```css
border-color: red;
border-color: blue;
```

### Actual Result
image

### Version
0.14.0

### PR DESCRIPTION
**Pull request by miroslavstastny**
Fixes #572 

`color: ['red', 'blue']` is a valid style but `felaSanitizeCssPlugin` converted this to following object:

```js
color: {
  0: 'red',
  1: 'blue'
}
```
which is incorrect. Now the plugin handles arrays correctly.

### CODE REVIEW

File: src/lib/felaSanitizeCssPlugin.ts [hunk 1]
```diff
@@ -39,7 +39,7 @@ export default (config?: { skip?: string[] }) => {
   const cssPropertiesToSkip = [...((config && config.skip) || [])]
 
   const sanitizeCssStyleObject = styles => {
-    const processedStyles = {}
+    const processedStyles = Array.isArray(styles) ? [] : {}
 
     Object.keys(styles).forEach(cssPropertyName => {
       const cssPropertyValue = styles[cssPropertyName]
```
Comment (kuzhelov) [inline src/lib/felaSanitizeCssPlugin.ts]: nit: `cssPropertyName` -> `cssPropertyNameOrIndex`? Then intend would be easier to capture a week after :)

File: test/specs/lib/felaSanitizeCssPlugin-test.ts [hunk 2]
```diff
@@ -62,4 +62,13 @@ describe('felaSanitizeCssPlugin', () => {
 
     assertCssPropertyValue(`url('../../lib')`, true)
   })
+
+  describe('should pass arrays', () => {
```
Comment (kuzhelov) [inline test/specs/lib/felaSanitizeCssPlugin-test.ts]: A bit confused with the test name, as it doesn't provide some necessary insights to me. Specifically, here:`should pass array` - pass untouched? Process somehow? If process, then what is the logic that will be applied?

Would expect tests to cover the following logic:
> _if array is passed, then for each item of an array CSS styles sanitization should be applied_

**Review by kuzhelov — APPROVED** [review]
