### PR TITLE
fix(docs): component styles in RTL mode

### LINKED ISSUE #582: RTL mode breaks styles in docs
## Bug Report

When RTL mode is enabled for component example in docs, styles are not applied to rendered component. 

### Steps
- open component docs page of Stardust
- navigate to any component's page (say, `Segment`)
- enable RTL mode for any example

### Expected Result
Styles are properly rendered (preserved) for the rendered component.

### Actual Result
Styles completely disappear for rendered component.

image

image

### Version
0.13.1

### PR DESCRIPTION
**Pull request by kuzhelov**
Currently all the component styles are broken for docs in RTL mode. This PR fixes this problem.

## TODO
- [x] update changelog

## What was the issue

The root cause of that is the fact that Fela updates subscription to the DOM node where styles should be rendered to (i.e `<head> -> <styles>`) **only** on its Provider component being mounted.

It turns out that our rendering loigc hasn't guaranteed that new Fela's `Provider` will be mounted with RTL switch - and, this, the logic of <style> DOM node subscription wasn't fired for RTL renderer.

### Follow-up, general issue: #581

### CODE REVIEW

File: docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx [hunk 1]
```diff
@@ -260,7 +262,11 @@ class ComponentExample extends React.Component<ComponentExampleProps, ComponentE
       rtl: showRtl,
     }
 
-    return <Provider theme={newTheme}>{element}</Provider>
+    return (
+      <Provider key={`${examplePath}${showRtl ? '-rtl' : ''}`} theme={newTheme}>
```
Comment (levithomason) [inline docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx:266]: Perhaps this should be done in the Provider itself?  It seems adding it here would means RTL will work in our doc examples, but not necessarily anywhere else the Provider is used.

Comment (kuzhelov) [reply docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx:266]: not sure, as there is no straightforward way to **generate** the key (as we won't like to generate a new one on each rerendering). Should we request client to provide it?

Comment (kuzhelov) [reply docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx:266]: or you would suggest to do it here?

```jsx
// Provider.ts
...
   <ProviderConsumer
      render={(incomingTheme: ThemePrepared) => {
      const outgoingTheme: ThemePrepared = mergeThemes(incomingTheme, theme)

      return (
          <RendererProvider renderer={outgoingTheme.renderer} {...{ rehydrate: false }}>
             <ThemeProvider key={outgoingTheme.isRtl ? 'rtl' : 'ltr'} theme={outgoingTheme}>{children}</ThemeProvider>
          </RendererProvider>
       )
    }}
   />
```

**Review by levithomason — APPROVED** [review]
Just add a TODO and link to this issue to fix it in the Provider
