### PR TITLE
fix(MenuItem): prop types

### LINKED ISSUE #1112: Invalid PropTypes for MenuItem.menu (submenu)
### Steps
After #996 it is possible to specify `MenuItem.menu` as an array:
```jsx
const items: ShorthandCollection<MenuShorthandKinds> = [
  {
    key: 'editorials',
    content: 'Editorials',
    menu: [
        { key: '1', content: 'item1' },
        { key: '2', content: 'item2' },
      ],
  },
]
```

### Actual Result
image

### Version
0.25.0

### PR DESCRIPTION
**Pull request by kuzhelov**
Fixes #1112

### CODE REVIEW

File: packages/react/src/components/Menu/MenuItem.tsx [hunk 1]
```diff
@@ -105,7 +105,7 @@ export interface MenuItemProps
   wrapper?: ShorthandValue
 
   /** Shorthand for the submenu. */
-  menu?: ShorthandValue
+  menu?: ShorthandValue | ShorthandValue[]
```
Comment (layershifter) [inline packages/react/src/components/Menu/MenuItem.tsx]:
```suggestion
  menu?: ShorthandValue | ShorthandCollection
```

File: packages/react/src/components/Menu/MenuItem.tsx [hunk 2]
```diff
@@ -168,7 +168,10 @@ class MenuItem extends AutoControlledComponent<ReactProps<MenuItemProps>, MenuIt
     underlined: PropTypes.bool,
     vertical: PropTypes.bool,
     wrapper: PropTypes.oneOfType([PropTypes.node, PropTypes.object]),
-    menu: customPropTypes.itemShorthand,
+    menu: PropTypes.oneOfType([
+      customPropTypes.itemShorthand,
+      PropTypes.arrayOf(customPropTypes.itemShorthand),
```
Comment (layershifter) [inline packages/react/src/components/Menu/MenuItem.tsx]:
```suggestion
      customPropTypes.collectionShorthand,
```

**Review by layershifter — CHANGES_REQUESTED** [review]
Please use existing types for collections 🐰

**Review by layershifter — APPROVED** [review]
