### PR TITLE
fix(accessibility): apply accessibility handlers with `applyAccessibilityKeyHandlers()`

### LINKED ISSUE #799: Popup: accessibility behavior silently overrides user's props
## Bug Report

It's not possible to handle events on elements passed to `trigger` prop.
See, https://github.com/stardust-ui/react/blob/v0.19.1/src/components/Popup/Popup.tsx#L377

### Steps
1. Open example, https://codesandbox.io/s/1v66l6m647
2. Focus "Working" button, click "Enter" key, you will get "RAW KEYDOWN"
3. Focus "Working" button, click "Enter" key

### Expected Result
On step 3 you should get "NEVER HAPPEN!"

### Actual Result
`onKeyDown` handler was not called.

### Version
0.19.1

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #799.

### CODE REVIEW

**Comment by layershifter** [comment]
## Option 2: `mergeAccessibilityHandlers()` / `applyAccessibilityHandlers()`

Add function that will only merge `keyHanders`.
UPD, we decided:
```js
{...applyAccessibilityKeyHandlers(
  accessibility.keyHanders.root,
  { onKeyDown: this.handleKeyDown, ...unhandedProps },
)}
```

File: packages/react/src/lib/getKeyDownHandlers.ts [hunk 1]
```diff
@@ -57,8 +54,6 @@ const getKeyDownHandlers = (
 
           eventHandler && eventHandler(event)
         })
-
-        _.invoke(props, 'onKeyDown', event, props)
```
Comment (layershifter) [inline packages/react/src/lib/getKeyDownHandlers.ts:61]: This is wrong because it will be applied to each slot, see mini repro:
https://codesandbox.io/s/3kplmnz95q?module=/example.js
_When you will click `Enter` on dots, you will key `onKeyDown` twice_

File: packages/react/src/lib/applyAccessibilityKeyHandlers.ts [hunk 2]
```diff
@@ -0,0 +1,18 @@
+import * as _ from 'lodash'
+
+import { Props } from '../types'
+import { KeyboardHandler, OnKeyDownHandler } from './accessibility/types'
+
+const applyAccessibilityKeyHandlers = (keyHandlers: OnKeyDownHandler, passedProps: Props) =>
```
Comment (mnajdova) [inline packages/react/src/lib/applyAccessibilityKeyHandlers.ts]: Is the second argument really always going to be `Props`? If we want to use this functionality with the slots as well, should we receive here `ShorthandValue`? I know that the Popup has special handling of the `triggerProps`, but usually this is not the case...

Comment (layershifter) [reply packages/react/src/lib/applyAccessibilityKeyHandlers.ts]: Done, it makes sense because we also deal with slots 👍

File: packages/react/src/lib/applyAccessibilityKeyHandlers.ts [hunk 3]
```diff
@@ -0,0 +1,24 @@
+import * as _ from 'lodash'
+
+import { Props, ShorthandValue } from '../types'
+import { KeyboardHandler, OnKeyDownHandler } from './accessibility/types'
+
+const applyAccessibilityKeyHandlers = (
+  keyHandlers: OnKeyDownHandler,
+  value: Props | ShorthandValue,
+) => {
+  const slotProps: Props = typeof value === 'object' ? value : {}
```
Comment (mnajdova) [inline packages/react/src/lib/applyAccessibilityKeyHandlers.ts]: Let's not ignore the other cases of shorthand value. Let's refactor this in the same way it is done in the factories, something like:
```  
  const valIsPropsObject = _.isPlainObject(value)
  const valIsReactElement = React.isValidElement(value)

  const slotProps =
    (valIsReactElement && (value as React.ReactElement<Props>).props) ||
    (valIsPropsObject && (value as Props)) ||
    {}
```

**Review by mnajdova — APPROVED** [review]
