### PR TITLE
fix(mixed): correct types to match propTypes

### LINKED ISSUE #548: Typings: correct typings to match propTypes
## Bug Report

The latest release of [@types/react](https://www.npmjs.com/package/@types/react) with TS 3.2 breaks all our builds on **Project Tests** stage.

### Steps

Build any PR.

### Expected Result

CI pass.

### Actual Result

image

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #548.

---

[TS sandbox with types](http://www.typescriptlang.org/play/#src=export%20type%20Extendable%3CT%3E%20%3D%20T%20%26%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%20any%0D%0A%7D%0D%0A%0D%0Aexport%20type%20Nullable%3CT%3E%20%3D%20T%20%7C%20null%0D%0Aexport%20type%20NullableIfUndefined%3CT%3E%20%3D%20T%20extends%20undefined%20%3F%20Nullable%3CT%3E%20%3A%20T%0D%0A%0D%0A%0D%0Aexport%20type%20ReactPropsStrict%3CT%3E%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20NullableIfUndefined%3CT%5BK%5D%3E%20%7D%0D%0Aexport%20type%20ReactProps%3CT%3E%20%3D%20Extendable%3CReactPropsStrict%3CT%3E%3E%0D%0A%0D%0A%2F%2F%20---%0D%0A%0D%0Aexport%20const%20testA%3A%20ReactProps%3C%7B%20a%3F%3A%20string%2C%20b%3A%20string%20%7D%3E%20%3D%20%7B%0D%0A%20%20a%3A%20null%2C%0D%0A%20%20b%3A%20null%0D%0A%7D%0D%0A%0D%0Aexport%20const%20testB%3A%20ReactPropsStrict%3C%7B%20a%3F%3A%20string%20%7D%3E%20%3D%20%7B%0D%0A%20%20a%3A%20null%2C%0D%0A%20%20b%3A%20null%0D%0A%7D%0D%0A%0D%0Aexport%20const%20testC%3A%20ReactProps%3C%7B%20a%3F%3A%20string%20%7D%3E%20%3D%20%7B%0D%0A%20%20a%3A%20'string'%2C%0D%0A%20%20b%3A%20'string'%0D%0A%7D%0D%0A), don't forget to enable `strictNullChecks` in options 👍

### CODE REVIEW

File: src/components/Attachment/Attachment.tsx [hunk 1]
```diff
@@ -9,30 +9,30 @@ import {
...
+import { Extendable, Nullable, ShorthandRenderFunction, ShorthandValue } from '../../../types/utils'
 import Icon from '../Icon/Icon'
 import Button from '../Button/Button'
 import Text from '../Text/Text'
 import Slot from '../Slot/Slot'
 
 export interface AttachmentProps extends UIComponentProps, ChildrenComponentProps {
   /** Button shorthand for the action slot. */
-  action?: ShorthandValue
+  action?: Nullable<ShorthandValue>
```
Comment (kuzhelov) [inline src/components/Attachment/Attachment.tsx]: maybe it would be easier to use generic type that will be able to transform entire props type, like that:

```jsx
export interface AttachmentProps {
  action?: ShorthandValue,
  ...
}

class Attachment extends UIComponent<Nullable<AttachmentProps>, ...>
```

**Comment by layershifter** [comment]
I don't understand this:

image

image

🦀

**Comment by layershifter** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30874
https://github.com/Microsoft/TypeScript/issues/28631

👎

File: types/utils.d.ts [hunk 2]
```diff
@@ -24,6 +27,10 @@ export type ObjectOrFunc<TResult, TArg = {}> = ((arg: TArg) => TResult) | TResul
 
 export type Props = ObjectOf<any>
 export type ReactChildren = React.ReactNodeArray | React.ReactNode
+
+export type ReactPropsStrict<T> = { [K in keyof T]: NullableIfUndefined<T[K]> }
+export type ReactProps<T> = Extendable<ReactPropsStrict<T>>
```
Comment (layershifter) [inline types/utils.d.ts:32]: There is a small difference, `ReactPropsStrict` cannot be extended it's very useful for `Portal`, `Ref` and other component that don't allow to spread props.

File: src/lib/factories.tsx [hunk 3]
```diff
@@ -195,7 +195,7 @@ function createShorthandFromValue(
   if (valIsReactElement) return React.cloneElement(value as React.ReactElement<Props>, props)
 
   // Create ReactElements from built up props
-  if (valIsPrimitive || valIsPropsObject) return <Component {...props} />
+  if (valIsPrimitive || valIsPropsObject) return React.createElement(Component, props)
```
Comment (layershifter) [inline src/lib/factories.tsx:200]: Is it a suite strange change? YES!

----

https://github.com/Microsoft/TypeScript/issues/28768
https://github.com/Microsoft/TypeScript/issues/28631#issuecomment-443194203

**Comment by layershifter** [comment]
#608 showed that a build can be passed, I will try to fix all remaining errors to be compatible with the latest TS.

File: docs/src/examples/components/Ref/Types/RefForwardingExample.tsx [hunk 4]
```diff
@@ -1,7 +1,7 @@
 import React from 'react'
 import { Grid, Ref, Segment } from '@stardust-ui/react'
 
-const ExampleButton = React.forwardRef<HTMLButtonElement>((props, ref) => (
+const ExampleButton = React.forwardRef<HTMLButtonElement, { children: string }>((props, ref) => (
```
Comment (layershifter) [inline docs/src/examples/components/Ref/Types/RefForwardingExample.tsx]: It becomes more problematic, we should force #495.

File: docs/src/prototypes/popups/GridImagePicker/GridImagePickerItem.tsx [hunk 5]
```diff
@@ -17,19 +16,15 @@ const imageButtonStyles = {
...
-    as: 'li',
-  }
-
   render() {
-    const { title, imageSrc, as: ElementType, onClick } = this.props
+    const { title, imageSrc, onClick } = this.props
 
     return (
-      <ElementType>
+      <li>
```
Comment (layershifter) [inline docs/src/prototypes/popups/GridImagePicker/GridImagePickerItem.tsx:23]: This didn't make any reasonable sense, but caused my favourite error, https://github.com/Microsoft/TypeScript/issues/28768

File: src/lib/accessibility/FocusZone/FocusTrapZone.types.tsx [hunk 6]
```diff
@@ -1,3 +1,5 @@
+import * as React from 'react'
```
Comment (layershifter) [inline src/lib/accessibility/FocusZone/FocusTrapZone.types.tsx:1]: This import was absent before

File: types/utils.d.ts (hunk 2 above)
Comment (miroslavstastny) [inline types/utils.d.ts:32]: So when I should use `Extendable` vs `ReactProps`? My understanding is I should always use `ReactProps` (or `ReactPropsStrict` in special cases).
But for example `Dropdown` is still using `Extendable`.
Shouldn't we remove `Extendable` completely?

**Review by miroslavstastny — APPROVED** [review]

File: types/utils.d.ts (hunk 2 above)
Comment (layershifter) [reply types/utils.d.ts:32]: `Dropdown` should use `ReactProps`, too. I missed it, will check all `Dropdown`'s components.

> Shouldn't we remove Extendable completely?

Note sure, it's a quite generic type, we're using it in `theme/types.ts` for colors and props.
