### PR TITLE
fix(Status): fix order of applied props

### LINKED ISSUE #958: Status: can't override `role` attribute
## Bug Report

I can't override `role` attribute.

### Steps
```jsx
<Status role='presentation' />
```

### Expected Result
```html
<span role="presentation" class="ui-status co ec ch ci hz ia y ib ic"></span>
```

### Actual Result
```html
<span role="img" class="ui-status co ec ch ci hz ia y ib ic"></span>
```
💣

### Version
master

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #958.

### CODE REVIEW

File: packages/react/test/specs/commonTests/isConformant.tsx [hunk 1]
```diff
@@ -319,18 +329,24 @@ export default (Component, options: Conformant = {}) => {
...
-      })
-
       const wrapper = mount(<Component {...requiredProps} accessibility={noopBehavior} />)
       const element = getComponent(wrapper)
 
+      expect(element.prop(IS_FOCUSABLE_ATTRIBUTE)).toBe(true)
       expect(element.prop('role')).toBe(role)
     })
+
+    test('attributes passed by consumer has more weight', () => {
```
Comment (kuzhelov) [inline packages/react/test/specs/commonTests/isConformant.tsx]: nit-nit: maybe we could just state supported scenario, like `client's attributes override the ones provided by Stardust`

File: packages/react/test/specs/commonTests/isConformant.tsx [hunk 2]
```diff
@@ -319,18 +329,24 @@ export default (Component, options: Conformant = {}) => {
...
+      const wrapper = mount(
+        <Component
+          {...{ ...requiredProps, [IS_FOCUSABLE_ATTRIBUTE]: false }}
```
Comment (kuzhelov) [inline packages/react/test/specs/commonTests/isConformant.tsx]: would suggest to make it a bit more readable: 

```jsx
const clientAttributes = {
   [IS_FOCUSABLE_ATTRIBUTE]: false,
   accessibility: noopBehavior
}

const wrapper = mount(<Component {...requiredProps} {...clientAttributes} />
...
```

File: packages/react/test/specs/commonTests/isConformant.tsx (hunk 1 above)
Comment (kuzhelov) [inline packages/react/test/specs/commonTests/isConformant.tsx]: 👍 thanks for adding this one!

**Review by kuzhelov — APPROVED** [review]
would like @jurokapsiar to take a look on these changes, just to be absolutely sure this strategy won't get into conflict with existing accessibility behaviours
