### PR TITLE
fix(SSR): fix document usage and add project test

### LINKED ISSUE #2182: Reference to document is breaking serverside rendering
## Bug Report

We're attempting to serverside render our app, but a few references to `document` in `
mergeProviderContexts.ts` makes it throw:
```
ReferenceError: document is not defined at mergeProviderContexts 
```
I found a previous commit in the project that removed references to `window` and `document`, I'm guessing with the intent of allowing serverside rendering, but in this specific case the usage was allowed with the use of `// eslint-disable-line no-undef`.

Am I missing something? Is there a yet-to-be documented configuration that would allow serverside rendering? Or is it simply not supported by the project yet?

### Version
0.42.0

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #2182.

This PR:
- fixes issues described in linked issue
- adds a project test to be sure that we can build Fluent in SSR environment

### CODE REVIEW

File: packages/react/src/utils/UIComponent.tsx [hunk 1]
```diff
@@ -29,6 +30,7 @@ class UIComponent<P, S = {}> extends React.Component<P, S> {
   }
 
   actionHandlers: AccessibilityActionHandlers
+  context: ProviderContextPrepared
```
Comment (layershifter) [inline packages/react/src/utils/UIComponent.tsx:33]: Let's finally type this thing 🚀

**Review by miroslavstastny — APPROVED** [review]
