### PR TITLE
fix(Icon): revert changes with different roots

### LINKED ISSUE #1407: Icon backgroundColor not working
### Steps

```jsx
<Icon
   name="accept"
   circular
   styles={{ color: 'red', backgroundColor: 'green' }}
   size="smallest"
/>
```

### Expected Result

Background color is changed according to provided styling. This worked in 0.29.1

image

### Actual Result

Background color style did not propagate

image

### Version
0.31.0

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1407.

Reverts changes with multiple roots from #1337 (`svgRoot` & `fontRoot`). This idea breaks ability to override styles via `styles` prop on `Icon` component: `svgRoot` & `fontRoot` had more priority on merge. Also we used `Box` component there, it's redundant.

We definitely will want to separate these styles somehow to avoid conditions, but `svgRoot`/`fontRoot` is definitely bad stuff.

### CODE REVIEW

File: packages/react/src/themes/font-awesome/components/Icon/iconStyles.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@ import { IconProps } from '../../../../components/Icon/Icon'
 import { IconVariables } from '../../../teams/components/Icon/iconVariables'
 
 const iconStyles: ComponentSlotStylesInput<IconProps, IconVariables> = {
-  fontRoot: (): ICSSInJSStyle => ({
+  root: (): ICSSInJSStyle => ({
```
Comment (mnajdova) [inline packages/react/src/themes/font-awesome/components/Icon/iconStyles.ts]: Shuold we add this conditionally if the icon is font icon? Won't this break icons on docs?

Comment (mnajdova) [reply packages/react/src/themes/font-awesome/components/Icon/iconStyles.ts]: I check that it doesn't break anything, so not sure if you should implement the comment...

**Review by bmdalex — APPROVED** [review]
👍

**Review by mnajdova — APPROVED** [review]

File: packages/react/src/themes/font-awesome/components/Icon/iconStyles.ts (hunk 1 above)
Comment (kuzhelov) [reply packages/react/src/themes/font-awesome/components/Icon/iconStyles.ts]: agree that it is better to introduce explicit condition check here, as we are expecting this rule to be applied exclusively to font-based icons

**Review by kuzhelov — APPROVED** [review]
