### PR TITLE
perf(Tooltip): fix Popper positioning called when unnecessary

### LINKED ISSUE #1880: Popper in Tooltip always executes positioning code
## Bug Report

The `Tooltip`'s `Popper`'s positioning code is always executed, even if the tooltip content is not visible to the user. This is a performance issue if we have many `Tooltip` components.

### Expected Result
The content positioning code is only executed when the content is visible to the user.

### Actual Result
The content positioning code is executed even if the content is not visible 💣

### Version
0.37.0

### PR DESCRIPTION
**Pull request by lucivpav**
Fixes #1880

### CODE REVIEW

File: packages/react/src/components/Tooltip/Tooltip.tsx [hunk 1]
```diff
@@ -238,6 +242,7 @@ export default class Tooltip extends AutoControlledComponent<TooltipProps, Toolt
         pointerTargetRef={this.pointerTargetRef}
         align={align}
         position={position}
+        enabled={this.state.open}
```
Comment (layershifter) [inline packages/react/src/components/Tooltip/Tooltip.tsx]:
```diff
    const { align, position, target } = this.props
+    const { open } = this.state
```

```suggestion
        enabled={open}
```

_nit:_ to aligned let's use destruction

File: packages/react/test/specs/components/Tooltip/Tooltip-test.tsx [hunk 2]
```diff
@@ -60,4 +60,13 @@ describe('Tooltip', () => {
       )
     })
   })
+
+  describe('open', () => {
+    it('is passed to "Popper" as "enabled"', () => {
+      const wrapper = mountWithProvider(<Tooltip trigger={<button />} content="Foo" />)
+      expect(wrapper.find('Popper').prop('enabled')).toBe(false)
+      wrapper.setProps({ open: true })
```
Comment (layershifter) [inline packages/react/test/specs/components/Tooltip/Tooltip-test.tsx:69]:
```suggestion

      wrapper.setProps({ open: true })
```

nit: empty line

**Review by layershifter — APPROVED** [review]
