### PR TITLE
fix(Popup): Focus the last focused element outside Popup on ESC

### LINKED ISSUE #831: Popup triggered by MenuItem is focusing the wrapper instead of the root when user presses ESC
## Bug Report
Popup has the ability to focus trigger element when it is closed by ESC key.
This does not work properly with MenuItem - in that case, the element to be triggered needs to be the root (a), not the wrapper (li) element.

### Testcase
https://codesandbox.io/s/mql1160ll8?module=/example.js

### PR DESCRIPTION
**Pull request by sophieH29**
This PR fixes the issue when a complex component is used as a trigger for Popup, but actually, the inner element of that component triggers the Popup. So when press ESC on Popup, the focus should go to the actual focusable element which triggered the Popup, not the whole component itself.

In the next example, `MenuItem` is a trigger for the Popup and this component has this structure
```jsx
<li> - wrapper
   <a></a> // focusable element which actually triggers Popup
</li>

```

```jsx
const items = [
  {
    key: 'editorials',
    content: 'Editorials',
  },
  {
    key: 'review',
    content: 'Reviews',
  },
  {
    key: 'events',
    content: 'Upcoming Events',
  },
].map(item => render => render(item, renderIten))

const renderIten = (MenuItem, props) =>
  <Popup
    content={{ content: <Button content="Click me" /> }}
    trigger={<MenuItem {...props}/>}
  />

const MenuExample = () => <Menu defaultActiveIndex={0} items={items} />
```

So when press ESC, `MenuItem`'s wrapper `<li>` element will receive focus, instead of `<a>`, what breaks focus management on the page.

Closes https://github.com/stardust-ui/react/issues/831

### CODE REVIEW

**Review by jurokapsiar — APPROVED** [review]

File: packages/react/src/components/Popup/Popup.tsx [hunk 1]
```diff
@@ -474,6 +476,8 @@ export default class Popup extends AutoControlledComponent<ReactProps<PopupProps
   }
 
   private trySetOpen(newValue: boolean, eventArgs: any) {
+    // when new state 'open' === 'true', save the last focused element
+    newValue && this.updateTriggerFocusableDomElement()
```
Comment (layershifter) [inline packages/react/src/components/Popup/Popup.tsx]:
```suggestion
    if (newValue) this.updateTriggerFocusableDomElement()
```

```suggestion
    if (newValue) {
      this.updateTriggerFocusableDomElement()
    }
```

Let's make it more readable.

File: packages/react/src/components/Popup/Popup.tsx [hunk 2]
```diff
@@ -497,4 +501,14 @@ export default class Popup extends AutoControlledComponent<ReactProps<PopupProps
       onClose && onClose()
     }
   }
+
+  /**
+   * Save DOM element which had focus before Popup opens.
+   * Can be either trigger DOM element itself or the element inside it.
+   */
+  private updateTriggerFocusableDomElement() {
```
Comment (layershifter) [inline packages/react/src/components/Popup/Popup.tsx:511]: Do we need to introduce a new method for a single use?

Comment (sophieH29) [reply packages/react/src/components/Popup/Popup.tsx:511]: I think it makes sense, don't want to mess up `tryOpen` method and still remain better reading

**Review by layershifter — APPROVED** [review]
