### PR TITLE
fix(MenuDivider): not shown when used on horizontal menus

### LINKED ISSUE #722: Menu Divider doesn't work with iconOnly + horizontal menu
## Bug Report
Menu divider doesn't show up when the menu is horizontal and has iconOnly prop

### Steps
A clear and concise description of steps to reproduce the problem.

```jsx
import React from 'react'
import { Menu } from '@stardust-ui/react'
const items = [
  {
    key: 'editorials',
    icon: 'teams',
  },
  {
    key: 'review',
    icon: 'format',
  },
  {
    key: 'divider',
    kind: 'divider',
  },
  {
    key: 'events',
    icon: 'bold',
  },
]

const MenuExample = () => <Menu defaultActiveIndex={0} items={items} iconOnly  />

export default MenuExample

```

### Expected Result
Divider should show up in the right place

### Actual Result
No divider

### Version
0.16.2

### PR DESCRIPTION
**Pull request by mnajdova**
This PR fixes https://github.com/stardust-ui/react/issues/722 The Divider is not shown on all menus, and the margins on different menus are fixed.

image

image

### CODE REVIEW

**Review by kuzhelov — APPROVED** [review]

File: src/themes/teams/components/Menu/menuStyles.ts [hunk 1]
```diff
@@ -42,4 +42,13 @@ export default {
       listStyleType: 'none',
     }
   },
+  divider: ({ props: { pointing, vertical, pills, underlined } }) => ({
+    ...(pointing &&
+      vertical && {
+        marginBottom: `${pxToRem(12)}`,
```
Comment (kuzhelov) [inline src/themes/teams/components/Menu/menuStyles.ts]: have agreed with @mnajdova to prevent duplication of `pxToRem` styles between `MenuDivider` and `MenuItem` styles
