### PR TITLE
fix(menuButton) - accessibility - add aria-controls attribute, when exists

### LINKED ISSUE #2084: SplitButton - Acc Insights for Web show error for  aria-controls attribute
### Steps
Run Accessibility Insights for Web for the SplitButton page.

### Expected Result / Actual Result

image

### PR DESCRIPTION
**Pull request by kolaps33**
Fixes #2084

### CODE REVIEW

**Review by jurokapsiar — APPROVED** [review]

**Review by jurokapsiar — APPROVED** [review]

File: packages/react/test/specs/components/MenuButton/MenuButton-test.tsx [hunk 1]
```diff
@@ -71,27 +71,23 @@ describe('MenuButton', () => {
...
         )
-        const button = menuButton.find('button')
-        button.simulate('click')
-        const menu = menuButton.find('ul')
-        const menuId = menu.prop('id')
+        menuButton.find('button').simulate('click')
 
-        expect(menuId).toEqual('test-id')
-        expect(button.prop('aria-controls')).toEqual(menuId)
+        expect(menuButton.find('ul').prop('id')).toEqual('test-id')
```
Comment (mnajdova) [inline packages/react/test/specs/components/MenuButton/MenuButton-test.tsx]:
```suggestion
        expect(menuButton.find('ul').prop('id')).toEqual(menuId)
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -25,6 +25,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 - Apply unhandled props of `Ref` to the children if used @jurokapsiar ([#2105](https://github.com/microsoft/fluent-ui-react/pull/2105))
 - Add necessary `-ms-grid-` styles to `Layout` for IE11 @jurokapsiar ([#2106](https://github.com/microsoft/fluent-ui-react/pull/2106))
 - Accessibility `splitButton` & `menuButton` - screen reader fixes @kolaps33 ([#2090](https://github.com/microsoft/fluent-ui-react/pull/2090))
+- Accessibility `menuButton` add aria-controls attribute, when exists @kolaps33 ([#2107](https://github.com/microsoft/fluent-ui-react/pull/2107))
```
Comment (mnajdova) [inline CHANGELOG.md]:
```suggestion
- Accessibility `menuButton` add aria-controls attribute based on `open` prop @kolaps33 ([#2107](https://github.com/microsoft/fluent-ui-react/pull/2107))
```

**Review by mnajdova — APPROVED** [review]
Please see comments before merging
