### PR TITLE
fix(ComponentSidebar): remove empty item in docs sidebar

### LINKED ISSUE #616: Docs: empty item in component sidebar
### Steps
1. Open any docs page:
https://stardust-ui.github.io/react/components/button
https://stardust-ui.github.io/react/components/form

### Expected Result
The empty item is present.

### Actual Result

image

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #616.

### CODE REVIEW

File: docs/src/components/ComponentDoc/ComponentSidebar/ComponentSidebar.tsx [hunk 1]
```diff
@@ -13,27 +12,29 @@ const sidebarStyle = {
...
   state: any = {}
 
   componentDidMount() {
-    this.fetchSections()
+    this.fetchSections(this.props.displayName)
   }
 
-  componentWillReceiveProps(nextProps) {
-    this.fetchSections(nextProps)
+  componentDidUpdate(prevProps: ComponentSidebarProps) {
```
Comment (layershifter) [inline docs/src/components/ComponentDoc/ComponentSidebar/ComponentSidebar.tsx:29]: Switched from deprecated `componentWillReceiveProps`

File: docs/src/components/ComponentDoc/ComponentSidebar/ComponentSidebar.tsx [hunk 2]
```diff
@@ -13,27 +12,29 @@ const sidebarStyle = {
...
+    if (this.props.displayName !== prevProps.displayName) {
+      this.fetchSections(this.props.displayName)
+    }
   }
 
-  fetchSections = ({ displayName } = this.props) => {
+  fetchSections = (displayName: string) => {
     import(`docs/src/exampleMenus/${displayName}.examples.json`).then(sections => {
-      this.setState({ sections })
+      this.setState({ sections: sections.default })
```
Comment (layershifter) [inline docs/src/components/ComponentDoc/ComponentSidebar/ComponentSidebar.tsx:37]: `import()` returned all exported keys, but also returned `default`

```js
{
  section1: '',
  section2: '',
  default: {
    section1: '',
    section2: '',
  }
}
```

**Review by alinais — APPROVED** [review]

**Review by miroslavstastny — APPROVED** [review]
