### PR TITLE
fix(Popup): proptypes for content and trigger

### LINKED ISSUE #1419: Popup: PropTypes when using ChildrenAPI
### Steps
```jsx
<Popup content="This popup is rendered next to the trigger." inline>
  <Button icon="expand" />
</Popup>
```

### Expected Result
- it is possible to use `content` and `children` together
- is is NOT possible to use `trigger` and `children` together

### Actual Result
image

### Version
0.31.0

### PR DESCRIPTION
**Pull request by miroslavstastny**
Fixes #1419.

### Expected behavior (provided by PR's changes)
It is possible to use `content` + `children`.
It is not possible to use `trigger` + `children`.

### CODE REVIEW

**Review by bmdalex — APPROVED** [review]
👍 I was about to create issue on this one, thanks for fixing!

File: packages/react-proptypes/src/index.ts [hunk 1]
```diff
@@ -375,14 +375,20 @@ export const wrapperShorthand = PropTypes.oneOfType([
...
+
 /**
  * Item shorthand is a description of a component that can be a literal,
  * a props object, an element or a render function.
  */
-export const itemShorthand = every([
-  disallow(['children']),
-  PropTypes.oneOfType([PropTypes.node, PropTypes.object, PropTypes.func]),
-])
+export const itemShorthand = every([disallow(['children']), shorthandAllowingChildren])
```
Comment (layershifter) [inline packages/react-proptypes/src/index.ts]: It breaks the initial idea of shorthands:

```jsx
<Button icon='book'>Click me</Button> // broken, propTypes warning 💣 
<Button icon='book' content='Click me' /> // works 🎉 
```
