### PR TITLE
fix(Accordion.Title): make contentRef prop optional

### LINKED ISSUE #1417: Accordion.Title contentRef prop is required
### Steps
Try use `Accordion` component with `Accordion.Title` subcomponent without specifying `contentRef` prop.

### Expected Result
It should be possible and should work without errors. 

### Actual Result
`contentRef` is a required prop but there is no reason for it. Stardust strives to create components that work out of the box with minimal props ➡️  `Accordion.Title` should work fine without specifying required props  💣

https://github.com/stardust-ui/react/blob/c69313cd008cf380d9ac2913342d0d403a398a05/packages/react/src/components/Accordion/AccordionTitle.tsx#L45

### Version
UNRELEASED

### PR DESCRIPTION
**Pull request by bmdalex**
### fix(Accordion.Title): make contentRef prop optional

Fixes #1417

### CODE REVIEW

**Review by kuzhelov — APPROVED** [review]

File: packages/react/src/components/Accordion/AccordionTitle.tsx [hunk 1]
```diff
@@ -42,7 +42,7 @@ export interface AccordionTitleProps
   index?: number
 
   /** Ref to the clickable element that contains the title. */
-  contentRef: React.Ref<HTMLElement>
+  contentRef?: React.Ref<HTMLElement>
```
Comment (silviuaavram) [inline packages/react/src/components/Accordion/AccordionTitle.tsx:45]: is it possible to also remove the `_.noop` from the tests?

**Review by silviuaavram — CHANGES_REQUESTED** [review]

File: packages/react/test/specs/components/Accordion/AccordionTitle-test.tsx [hunk 2]
```diff
@@ -8,26 +6,17 @@ describe('AccordionTitle', () => {
...
   })
 
   describe('accessiblity', () => {
     describe('header', () => {
       handlesAccessibility(AccordionTitle, {
-        requiredProps: {
-          as: 'h3',
-          contentRef: _.noop,
-        },
+        requiredProps: { as: 'h3' },
```
Comment (bmdalex) [inline packages/react/test/specs/components/Accordion/AccordionTitle-test.tsx:14]: @silviuavram are these changes correct? also why is `requiredProps: { as: 'h3' },` needed?

File: packages/react/src/components/Accordion/AccordionTitle.tsx (hunk 1 above)
Comment (bmdalex) [reply packages/react/src/components/Accordion/AccordionTitle.tsx:45]: done, pls check https://github.com/stardust-ui/react/pull/1418/files#r288565651

File: packages/react/test/specs/components/Accordion/AccordionTitle-test.tsx (hunk 2 above)
Comment (silviuaavram) [reply packages/react/test/specs/components/Accordion/AccordionTitle-test.tsx:14]: if it's a header it will not receive a role. you can see that the example below does not have the as prop as required, but the `handlesAccessibility` test will check that the role of `header` has been added.

**Review by silviuaavram — APPROVED** [review]

File: packages/react/test/specs/components/Accordion/AccordionTitle-test.tsx (hunk 2 above)
Comment (bmdalex) [reply packages/react/test/specs/components/Accordion/AccordionTitle-test.tsx:14]: got it, so the changes are good, thanks

**Review by layershifter — APPROVED** [review]
