### PR TITLE
docs(pages): fix broken links in docs

### LINKED ISSUE #1210: Docs: anchor links next to each header are broken
## Bug Report

image

### LINKED ISSUE #1285: Docs: "Read more about FocusZone." leads to 404
## Bug Report
The "Read more about FocusZone." link in the https://stardust-ui.github.io/react/accessibility#focus-zone docs leads to a 404 link: https://stardust-ui.github.io/focus-zone
As do the "read more" links for Focus Trap Zone and Auto Focus Zone

### Version
0.29.1

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1210.
Fixes #1285.

---

This PR fixes two issues with links.

#### Anchor links

We `<base>` to properly load images in examples and other stuff, however it introduces an issue with anchor links. See https://stackoverflow.com/questions/8108836/make-anchor-links-refer-to-the-current-page-when-using-base for more context.

#### Broken relative links that use `link()` helper

This helper should use `<Link>` from React Router that will properly handle `basename`.

### CODE REVIEW

File: docs/src/utils/helpers.tsx [hunk 1]
```diff
@@ -1,10 +1,20 @@
...
 export const code = value => <code>{value}</code>
 
-export const link = (content, href, isExternal = false) => (
-  <a href={href} {...isExternal && { target: 'blank' }}>
-    {content} {isExternal ? <Icon name="external" size="small" /> : ''}
-  </a>
-)
+export const link = (content: string, href: string) => {
+  const isExternal = href.startsWith('http://') || href.startsWith('https://')
+  const isAnchor = !isExternal && href.includes('#')
```
Comment (miroslavstastny) [inline docs/src/utils/helpers.tsx]: `includes` -> `startsWith`?

**Review by miroslavstastny — APPROVED** [review]

**Review by sophieH29 — APPROVED** [review]
