### PR TITLE
fix(Embed): get rid of white flash

### LINKED ISSUE #1586: Embed video has a white flash when toggle active state
## Bug Report
When playing or pausing an embedded video there is a white flash when switching between the placeholder and the video. This is particualry annoying when the placeholder is the first frame of the video.

### Steps
Create an Embed component and press play

### Expected Result
Playing a video should smoothly show the video.

### Actual Result
There is a whiteflash before the video starts

### Version
0.34.0

### Testcase
https://codesandbox.io/s/stardust-ui-example-fm1ow

### PR DESCRIPTION
**Pull request by lucivpav**
Now, when you activate a `video` or `iframe` `Embed`, no white flash appears. Instead, the placeholder image is used.

Fixes #1586

### CODE REVIEW

File: packages/react/src/components/Embed/Embed.tsx [hunk 1]
```diff
@@ -142,25 +151,27 @@ class Embed extends AutoControlledComponent<WithAsProp<EmbedProps>, EmbedState>
...
               },
             })}
-            {Box.create(iframe, { defaultProps: { as: 'iframe', styles: styles.iframe } })}
+            {Box.create(iframe, {
+              defaultProps: {
+                as: 'iframe',
+                styles: styles.iframe,
+                style: { visibility: iframeLoaded ? 'visible' : 'hidden' },
+                onLoad: () => {
+                  this.setState({ iframeLoaded: true })
```
Comment (layershifter) [inline packages/react/src/components/Embed/Embed.tsx]: Should be handled in `overrideProps` otherwise `onLoad` passed by user will override our handler.

File: packages/react/src/components/Embed/Embed.tsx [hunk 2]
```diff
@@ -142,25 +151,27 @@ class Embed extends AutoControlledComponent<WithAsProp<EmbedProps>, EmbedState>
...
                   height: variables.height,
                 },
               },
             })}
-            {Box.create(iframe, { defaultProps: { as: 'iframe', styles: styles.iframe } })}
+            {Box.create(iframe, {
+              defaultProps: {
+                as: 'iframe',
+                styles: styles.iframe,
+                style: { visibility: iframeLoaded ? 'visible' : 'hidden' },
```
Comment (layershifter) [inline packages/react/src/components/Embed/Embed.tsx]: Move these styles into theme please.

Comment (lucivpav) [reply packages/react/src/components/Embed/Embed.tsx]: How do I access state in `EmbedStyles`?

Comment (layershifter) [reply packages/react/src/components/Embed/Embed.tsx]: It will be available under props, use there a mix of types (actually it's already there):

image

File: packages/react/src/components/Embed/Embed.tsx (hunk 1 above)
Comment (layershifter) [reply packages/react/src/components/Embed/Embed.tsx]: 1. Original handler is still not called.
2. Please move it to class method:

```tsx
handleFrameOverrides = (predefinedProps) => ({
  onLoad: (e: EVENT_TYPE) => {
     _.invoke(predefinedProps, 'onLoaded', e)
     this.setState({ iframeLoaded: true })
  }
}}
```

File: packages/react/src/components/Embed/Embed.tsx [hunk 3]
```diff
@@ -134,6 +142,7 @@ class Embed extends AutoControlledComponent<WithAsProp<EmbedProps>, EmbedState>
         {...unhandledProps}
         {...applyAccessibilityKeyHandlers(accessibility.keyHandlers.root, unhandledProps)}
       >
+        {iframe && active && !iframeLoaded && placeholderImage}
```
Comment (layershifter) [inline packages/react/src/components/Embed/Embed.tsx]: What does this condition? Is there way to simplify rendering there?
There is too many conditions to be honest.

Comment (lucivpav) [reply packages/react/src/components/Embed/Embed.tsx]: I have extracted it into a function, please check again

**Review by layershifter — APPROVED** [review]
