### PR TITLE
fix(Chat): properly position `actions` with `overflow`

### LINKED ISSUE #2298: Chat: unstable_overflow is broken in ChatMessage
### Steps
1. Open example https://microsoft.github.io/fluent-ui-react/components/chat/definition#usage-in-scrollable
2. Change values via knobs to `{ "height": "200px", "width": "200px" }`
3. Hover first item:

image

Result: is correct 👍 

4. Scroll to middle of container:

image

5. Hover first item again:

image

Wrong padding was computed 💣 

### Version
0.43.0

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #2298.

### CODE REVIEW

File: packages/react/src/components/Chat/ChatMessage.tsx [hunk 1]
```diff
@@ -115,7 +116,7 @@ export interface ChatMessageProps
 
 export interface ChatMessageState {
   focused: boolean
-  messageNode: HTMLElement
+  messageNode: HTMLElement | null
```
Comment (layershifter) [inline packages/react/src/components/Chat/ChatMessage.tsx]: Fixed type as it's initially `null`

File: packages/react/src/components/Chat/ChatMessage.tsx [hunk 2]
```diff
@@ -230,12 +231,9 @@ class ChatMessage extends UIComponent<WithAsProp<ChatMessageProps>, ChatMessageS
       return actionMenuElement
     }
 
-    const menuRect: DOMRect = (positionActionMenu &&
-      _.invoke(this.menuRef.current, 'getBoundingClientRect')) || {
-      height: 0,
-    }
-    const messageRect: DOMRect = (positionActionMenu &&
-      _.invoke(messageNode, 'getBoundingClientRect')) || { height: 0 }
```
Comment (layershifter) [inline packages/react/src/components/Chat/ChatMessage.tsx:246]: When we paired with @miroslavstastny we realized that `messageRect.height` is enough in this case

**Review by miroslavstastny — APPROVED** [review]
