### PR TITLE
test(Behaviors): Improve behaviors tests for FocusZone

### LINKED ISSUE #850: Behavior tests for focus zone have insufficient coverage
## Bug Report

We have currently in "testDefinitions.ts"  
function verifyFocusZones()
which do focusZone verification for:
- focusZone. mode
- prop isCurcularNavigation
- prop preventDefaultWhenHandled

other props in the focusZone are not tested currently.

Probably we need to introduce for each property new line under the *@specification

### PR DESCRIPTION
**Pull request by sophieH29**
fixes https://github.com/stardust-ui/react/issues/850, https://github.com/stardust-ui/react/issues/476

### CODE REVIEW

File: packages/react/test/specs/behaviors/testDefinitions.ts [hunk 1]
```diff
@@ -382,92 +387,112 @@ definitions.push({
...
-    verifyFocusZones(expectedFocusZone, actualFocusZone)
+    const expectedFocusZoneMode = FocusZoneMode.Embed
+    expect(actualFocusZone.mode).toBe(expectedFocusZoneMode)
   },
 })
 
-// [Circular navigation] Embeds FocusZone into component allowing circular arrow key navigation through the children of the component.
 definitions.push({
-  regexp: /Embeds FocusZone into component allowing circular arrow key navigation through the children of the component\./g,
+  regexp: /arrows key navigation in horizontal direction/g,
```
Comment (silviuaavram) [inline packages/react/test/specs/behaviors/testDefinitions.ts]: nit: `arrow` key navigation here and other rules and in examples

**Review by silviuaavram — APPROVED** [review]

**Review by jurokapsiar — APPROVED** [review]

**Review by bmdalex — APPROVED** [review]
👍
