### PR TITLE
fix(docs): Set maximum width for examples

### LINKED ISSUE #1317: Docs: wide example breaks docsite layout
### Steps
Have a wide example

### Expected Result
Example pane does not grow out of browser width.

### Actual Result
image

### Version
master

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

### PR DESCRIPTION
**Pull request by miroslavstastny**
Fixes #1317.

Before:
image

After:
image

The visible overflow is intentional.

### CODE REVIEW

File: docs/src/examples/components/Text/States/TextExampleTruncated.shorthand.tsx [hunk 1]
```diff
@@ -11,7 +11,7 @@ const [notTruncatedText, truncatedText] = [
 )
 
 const TextExampleTruncatedShorthand = () => (
-  <div style={{ overflow: 'hidden', textOverflow: 'ellipsis', width: 500 }}>
+  <div style={{ overflow: 'hidden', textOverflow: 'ellipsis' }}>
```
Comment (miroslavstastny) [inline docs/src/examples/components/Text/States/TextExampleTruncated.shorthand.tsx:14]: Reverted suboptimal fix from #1019

**Review by layershifter — APPROVED** [review]
