### PR TITLE
fix(Flex): FlexProps extends UIComponentProps

### LINKED ISSUE #1078: FlexProps and FlexItemProps do not extend UIComponentProps
## Bug Report

`FlexProps` and `FlexItemProps` does not extend `UIComponentProps` and `ChildrenComponentProps`

### Version
0.23.1

### PR DESCRIPTION
**Pull request by miroslavstastny**
`FlexProps` now extends `UIComponentProps`.
Fixes #1078

### CODE REVIEW

File: packages/react/src/components/Flex/Flex.tsx [hunk 1]
```diff
@@ -2,11 +2,11 @@ import * as PropTypes from 'prop-types'
...
 import * as _ from 'lodash'
 
-import { UIComponent, commonPropTypes } from '../../lib'
+import { UIComponent, commonPropTypes, UIComponentProps, ChildrenComponentProps } from '../../lib'
 import { ReactProps } from '../../types'
 import FlexItem from './FlexItem'
 
-export interface FlexProps {
+export interface FlexProps extends UIComponentProps, ChildrenComponentProps {
   [key: string]: any
```
Comment (layershifter) [inline packages/react/src/components/Flex/Flex.tsx]: This can be removed now 🔧 

```suggestion
```

File: packages/react/src/components/Flex/FlexItem.tsx [hunk 2]
```diff
@@ -2,11 +2,11 @@ import * as React from 'react'
...
 import cx from 'classnames'
 import * as _ from 'lodash'
-import { UIComponent, commonPropTypes } from '../../lib'
+import { UIComponent, commonPropTypes, UIComponentProps, ChildrenComponentProps } from '../../lib'
 import { mergeStyles } from '../../lib/mergeThemes'
-import { Extendable } from '../../types'
+import { ReactProps } from '../../types'
 
-export interface FlexItemProps {
+export interface FlexItemProps extends UIComponentProps, ChildrenComponentProps {
```
Comment (layershifter) [inline packages/react/src/components/Flex/FlexItem.tsx]:
```suggestion
export interface FlexItemProps extends UIComponentProps, ChildrenComponentProps<React.ReactElement<any> | ({ styles: TYPE, classes: string }) => React.ReactElement<any>> {
```

Comment (layershifter) [reply packages/react/src/components/Flex/FlexItem.tsx]: `children` definition should be corrected as I see

**Review by kuzhelov — APPROVED** [review]

**Comment by miroslavstastny** [comment]
This does not fix pointing menu which uses `::after` on selected item.

**Review by layershifter — APPROVED** [review]
