### PR TITLE
fix(Accessibility): Action handlers should respect modifiers

### LINKED ISSUE #1332: Accessibility: key actions don't account modifiers
## Bug Report
Key actions in behaviors will not account modifiers along the keyCodes.
### Steps
In a behavior
```
  keyActions: {
    root: {
      f1: {
        keyCombinations: [{ keyCode: keyboardKey.Tab, shiftKey: false }],
      },
      f2: {
        keyCombinations: [{ keyCode: keyboardKey.Tab, shiftKey: true }],
      },
    }.
   }
```
And in a component
```
  actionHandlers: AccessibilityActionHandlers = {
    f1: e => {
      console.log('F1')
    },
    f2: e => {
      console.log('F2')
    },
}
```

### Expected Result
When hitting Tab, expect log F1.
When hitting Tab + Shift, expect log F2

### Actual Result
On Tab + Shift, both F2 and F1 are logged.

### Version
0.29.1

### PR DESCRIPTION
**Pull request by sophieH29**
Fixes https://github.com/stardust-ui/react/issues/1332

### CODE REVIEW

**Review by layershifter — APPROVED** [review]

File: packages/react/src/lib/shouldHandleOnKeys.ts [hunk 1]
```diff
@@ -3,18 +3,26 @@ import * as keyboardKey from 'keyboard-key'
 import * as _ from 'lodash'
 import * as React from 'react'
 
+const shouldHandleModifier = (modifierValue: boolean, combinationValue?: boolean) => {
+  if (typeof combinationValue === 'undefined') {
```
Comment (kuzhelov) [inline packages/react/src/lib/shouldHandleOnKeys.ts]: `combinationValue === undefined` should be enough here, as `combinationValue` is guaranteed to be declared (local one)

File: packages/react/src/lib/shouldHandleOnKeys.ts [hunk 2]
```diff
@@ -3,18 +3,26 @@ import * as keyboardKey from 'keyboard-key'
...
+    return true
+  }
+
+  return modifierValue === combinationValue
+}
+
 const shouldHandleOnKeys = (
```
Comment (kuzhelov) [inline packages/react/src/lib/shouldHandleOnKeys.ts:14]: nit: may suggest to rename this method to `matchesAny`/`matchesAnyKeyCombination` - this will better reflect its semantics

File: packages/react/src/lib/shouldHandleOnKeys.ts [hunk 3]
```diff
@@ -3,18 +3,26 @@ import * as keyboardKey from 'keyboard-key'
 import * as _ from 'lodash'
 import * as React from 'react'
 
+const shouldHandleModifier = (modifierValue: boolean, combinationValue?: boolean) => {
```
Comment (kuzhelov) [inline packages/react/src/lib/shouldHandleOnKeys.ts]: nit: `isKeyModifiersMatch` will provide better idea on what this method is designed to check

**Review by kuzhelov — APPROVED** [review]

File: packages/react/src/lib/shouldHandleOnKeys.ts (hunk 2 above)
Comment (sophieH29) [reply packages/react/src/lib/shouldHandleOnKeys.ts:14]: I was renamed to `shouldHandleOnKeys` here https://github.com/stardust-ui/react/pull/1421 and most of the people approved. Frankly, I like it more as we know what is the expected answer we want to receive - if we need to handle keydown events. `matchesAnyKeyCombination ` - doesn't answer this question for me.
