### PR TITLE
fix(Popper): improve positioning in multiple cases

### LINKED ISSUE #2064: Popup clipping in RTL
## Bug Report
Popup clips in RTL, even if the frame is large enough to support it.
### Steps
A clear and concise description of steps to reproduce the problem.
Opening Popup in RTL from toolbar item can cause clipping on right side. While, not present in this example you can see strange/jumpy rendering behavior:

https://codesandbox.io/s/stardust-ui-example-rgm6n

### Expected Result
Popup opens normally, with no rendering shift or clipping in both RTL and LTR

### Actual Result
Popup clips and has strange rendering and can clip in RTL mode

### Testcase
[Fork, update, and replace this sandbox to show the bug]:
https://codesandbox.io/s/stardust-ui-example-8ismt

### LINKED ISSUE #2072: Incorrect popup placement after jump-resize
### Steps
1. Open a popup
2. Resize browser window using a hotkey to a half

### Expected Result
Popup correctly positioned

### Actual Result
Position is incorrect, next repositioning fixes that 💣
out

### Version
0.40.2

Introduced by #2067, this does not happen with GPU acceleration enabled.

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #2064.
Fixes #2072.

## Case 1: jump on focus

The same as https://github.com/mui-org/material-ui/issues/16740, when opening a `Popup` with an autofocus input inside it, should not cause the page to jump (scroll).

## Case 2: scrollbar sizing issues

> The situation arises when an element on the page has as height the entire viewport (100vh). Imagine the following DOM:
>
>What happens is that right before the computation of the position of the popper, the popper gets `position: absolute`. However, since the popper appears after the page in the DOM, it will be positioned after it as well. Since the height of the page then becomes 100vh + height(popper), the scrollbar appears.

***

See code comments for descriptions and linked issues.

### CODE REVIEW

**Review by miroslavstastny — APPROVED** [review]

File: packages/react/src/utils/positioner/Popper.tsx [hunk 1]
```diff
@@ -11,16 +11,28 @@ import getScrollParent from './getScrollParent'
...
+  popper: HTMLElement,
   options?: PopperJS.PopperOptions,
 ): PopperJS => {
   const instance = new ((_PopperJS as any).default || _PopperJS)(reference, popper, {
     ...options,
     eventsEnabled: false,
   })
+
+  const originalUpdate = instance.update
+  instance.update = () => {
```
Comment (miroslavstastny) [inline packages/react/src/utils/positioner/Popper.tsx:23]: Why the PR title says 'first render'? This fixes resizing after the first render.

Comment (layershifter) [reply packages/react/src/utils/positioner/Popper.tsx:23]: Updated 👍

**Comment by oliviertassinari** [comment]
😆
