### PR TITLE
fix(Provider): should not use felaRenderer explicitly

### LINKED ISSUE #1814: Provider doesn't always use props.renderer
`Provider` takes in an optional `renderer` prop to customize the Fela renderer used in the React tree. This prop is correctly passed down via context, but there are still places where Stardust's singleton are used. This means that two renderers can be active at once.

If the renderer is customized, Stardust should always prefer it over its own in order to better support server-side rendering.

Here are a few examples:

* https://github.com/stardust-ui/react/blob/6607278b148f9a9404c4ea48c93be9a75e3d6856/packages/react/src/components/Provider/Provider.tsx#L99
* https://github.com/stardust-ui/react/blob/6607278b148f9a9404c4ea48c93be9a75e3d6856/packages/react/src/components/Provider/Provider.tsx#L105
* https://github.com/stardust-ui/react/blob/6607278b148f9a9404c4ea48c93be9a75e3d6856/packages/react/src/components/Provider/Provider.tsx#L129

### Version
0.36.1

### Testcase
N/A

### PR DESCRIPTION
**Pull request by lucivpav**
Fixes #1814

### CODE REVIEW

**Review by layershifter — COMMENTED** [review]
Let's add some tests for it

File: packages/internal-tooling/eslint/index.js [hunk 1]
```diff
@@ -115,6 +115,12 @@ module.exports = {
         '@stardust-ui/no-visibility-modifiers': 'error',
       },
     },
+    {
+      files: '**/*.{ts,tsx}',
+      rules: {
+        'no-dupe-class-members': 'off',
```
Comment (lucivpav) [inline packages/internal-tooling/eslint/index.js:121]: Otherwise we get false positive in `RendererMock.tsx`, see https://github.com/typescript-eslint/typescript-eslint/issues/291

**Comment by lucivpav** [comment]
> Let's add some tests for it

@layershifter I have added tests. But I feel its a bit ugly to add `RendererMock.tsx` file. Can you point me to the right direction?

File: packages/react/test/specs/components/Provider/Provider-test.tsx [hunk 2]
```diff
@@ -184,4 +187,46 @@ describe('Provider', () => {
...
   })
+
+  describe('calls provided renderer', () => {
+    test('calls renderFont', () => {
+      const theme: ThemeInput = {
+        fontFaces: teams.fontFaces,
+      }
+
+      const renderFontCalled = jest.fn()
+      const rendererMock = new RendererMock(renderFontCalled, jest.fn())
```
Comment (layershifter) [inline packages/react/test/specs/components/Provider/Provider-test.tsx]: https://jestjs.io/docs/en/jest-object.html#jestspyonobject-methodname

Have you tried `spyOn` instead?

File: packages/react/test/specs/components/Provider/Provider-test.tsx [hunk 3]
```diff
@@ -184,4 +187,44 @@ describe('Provider', () => {
       })
     })
   })
+
+  describe('calls provided renderer', () => {
+    test('calls renderFont', () => {
+      const theme: ThemeInput = {
+        fontFaces: teams.fontFaces,
+      }
+      const renderer = createRenderer()
```
Comment (lucivpav) [inline packages/react/test/specs/components/Provider/Provider-test.tsx:201]: I cannot use `felaRenderer`, because the test would pass even without this fix.

File: packages/internal-tooling/eslint/index.js (hunk 1 above)
Comment (lucivpav) [reply packages/internal-tooling/eslint/index.js:121]: No longer needed at the moment, but I think it will be useful to keep this change, as described in the link above

Comment (layershifter) [reply packages/internal-tooling/eslint/index.js:121]: Yep, let's keep it

File: packages/react/test/specs/components/Provider/Provider-test.tsx [hunk 4]
```diff
@@ -184,4 +187,44 @@ describe('Provider', () => {
       })
     })
   })
+
+  describe('calls provided renderer', () => {
+    test('calls renderFont', () => {
+      const theme: ThemeInput = {
+        fontFaces: teams.fontFaces,
```
Comment (layershifter) [inline packages/react/test/specs/components/Provider/Provider-test.tsx]: Can we use some dumb definition instead?

**Review by layershifter — APPROVED** [review]
