### PR TITLE
fix(docs): createComponent typings and documentation

### LINKED ISSUE #946: Wrong documentation for `createComponent`
### Steps
- user wants to create a new component;
- user goes to documentation: https://stardust-ui.github.io/react/integrate-custom-components
- users picks first example:
screenshot 2019-02-22 at 12 26 28
- user pastes example in his TS file

### Expected Result
Example works as expected without errors

### Actual Result
We have compilation error on our own example from documentation 💣
screenshot 2019-02-22 at 12 25 30
screenshot 2019-02-22 at 12 25 44

### Version
v0.21.1

### PR DESCRIPTION
**Pull request by bmdalex**
### fix(docs): createComponent typings and documentation

FIxes #946 by:
- improving typings for `createComponent`
- improving `/integrate-custom-components` section in Documentation

### CODE REVIEW

File: packages/react/src/lib/createStardustComponent.tsx [hunk 1]
```diff
@@ -18,13 +20,13 @@ export interface CreateStardustComponentConfig<P> {
   actionHandlers?: AccessibilityActionHandlers
 }
 
-const createComponent = <P extends {} = {}, S extends {} = {}>({
+const createComponent = <P extends {} = ObjectOf<any>>({
```
Comment (bmdalex) [inline packages/react/src/lib/createStardustComponent.tsx]: I was also considering the more correct fix:
```suggestion
const createComponent = <P extends {} = React.HTMLAttributes<HTMLElement>>({
```
but for some reason we don't seem to be fans of typing our components as extensions of HTML elements 😕

**Review by alinais — APPROVED** [review]

File: packages/react/src/lib/createComponent.tsx [hunk 2]
```diff
@@ -22,7 +23,7 @@ export type CreateComponentReturnType<P> = React.FunctionComponent<P> & {
   create: Function
 }
 
-const createComponent = <P extends {} = {}, S extends {} = {}>({
+const createComponent = <P extends {} = ObjectOf<any>>({
```
Comment (kuzhelov) [inline packages/react/src/lib/createComponent.tsx]: seems that the intent is a bit different here: if we would like to restrict type to objects, I would suggest the following expression for that:
```js
const createComponent = <P extends ObjectOf<any> = {}>({ ...
```

File: packages/react/src/lib/createStardustComponent.tsx (hunk 1 above)
Comment (kuzhelov) [reply packages/react/src/lib/createStardustComponent.tsx]: yes - lets just start with loose but correct types for now, and steadily restrict them after. The same suggestion here:
```js
const createComponent = <P extends ObjectOf<any> = {}>({ ...
```

File: packages/react/src/lib/createComponent.tsx (hunk 2 above)
Comment (bmdalex) [reply packages/react/src/lib/createComponent.tsx]: @kuzhelov - your suggestion does not address that

the intent is to have `P` have `ObjectOf<any` by default so that we don't have the errors I mentioned in #946 for the case when we do not supply the props interface to `createComponent` 

From #946 description:

### Actual Result
We have compilation error on our own example from documentation 💣
screenshot 2019-02-22 at 12 25 30
screenshot 2019-02-22 at 12 25 44

File: packages/react/src/lib/createStardustComponent.tsx (hunk 1 above)
Comment (bmdalex) [reply packages/react/src/lib/createStardustComponent.tsx]: see https://github.com/stardust-ui/react/pull/954#discussion_r260265890

Comment (kuzhelov) [reply packages/react/src/lib/createStardustComponent.tsx]: yes - as a result, have agreed with @Bugaa92 to introduce the following type:

```js
const createComponent = <P extends ObjectOf<any> = {}>({ ..
```
This will prevent the following things:
```js
const Foo = createComponent<number>(...)
const Foo = createComponent<string>(...)
```
and, at the same time, will work properly for the scenarios @Bugaa92 has mentioned 👍

File: packages/react/src/lib/createComponent.tsx (hunk 2 above)
Comment (kuzhelov) [reply packages/react/src/lib/createComponent.tsx]: yes - as a result, have agreed with @Bugaa92 to introduce the following type:

```js
const createComponent = <P extends ObjectOf<any> = {}>({ ..
```
This will prevent the following things:
```js
const Foo = createComponent<number>(...)
const Foo = createComponent<string>(...)
```
and, at the same time, will work properly for the scenarios @Bugaa92 has mentioned 👍

Comment (bmdalex) [reply packages/react/src/lib/createComponent.tsx]: after discussions with @kuzhelov we agreed to go with `P extends ObjectOf<any> = any`

EDIT: haha one minute faster

File: packages/react/src/lib/createStardustComponent.tsx (hunk 1 above)
Comment (bmdalex) [reply packages/react/src/lib/createStardustComponent.tsx]: after discussions with @kuzhelov we agreed to go with `P extends ObjectOf<any> = any`

**Review by kuzhelov — APPROVED** [review]
