### PR TITLE
fix(factories): styles defined as func are not working

### LINKED ISSUE #415: Styles defined as functions in shorthand are not working
### Steps
Define some styles as a function in any shorthand of the components. For example, in the Button, define the icon shorthand with some styles in form of a function.

```
<Button 
  type="primary" 
  icon={{
    name: "book", 
    styles: () => ({margin:'10px'}),
  }} 
  content="Click me before" 
  iconPosition="before" />
```

### Expected Result
The styles should be applied for the shorthand.

### Actual Result
They are not applied. The only way that those are applied is if the styles are defined as object 💣

### Version
0.11.0

### PR DESCRIPTION
**Pull request by mnajdova**
## TODO
- [x] update CHANGELOG

--------------

This PR fixes https://github.com/stardust-ui/react/issues/415

### CODE REVIEW

File: test/specs/lib/factories-test.tsx [hunk 1]
```diff
@@ -264,7 +265,72 @@ describe('factories', () => {
...
+              ':hover': {
+                position: 'keep',
+                color: 'blue',
+              },
+            })
+          },
+        })
+      })
+
+      test('deep merges styles prop as function onto defaultProps styles', () => {
```
Comment (kuzhelov) [inline test/specs/lib/factories-test.tsx:280]: `into`? actually, was surprised to discover existence of `onto` word for myself :)

File: test/specs/lib/factories-test.tsx [hunk 2]
```diff
@@ -264,7 +265,72 @@ describe('factories', () => {
...
+              ':hover': { color: 'blue' },
+            })
+          },
+        })
+      })
+
+      test('deep merges overrideProps styles as function onto styles prop', () => {
+        expect.assertions(1)
+
+        const overrideProps = {
```
Comment (kuzhelov) [inline test/specs/lib/factories-test.tsx:309]: it might be a bit easier to reason about expected results if these two `props` objects will be swapped

File: src/lib/factories.tsx [hunk 3]
```diff
@@ -106,7 +107,13 @@ export function createShorthand(
 
   // Merge styles
   if (defaultProps.styles || overrideProps.styles || usersProps.styles) {
-    props.styles = _.merge(defaultProps.styles, usersProps.styles, overrideProps.styles)
+    props.styles = (...args) => {
+      return _.merge(
```
Comment (kuzhelov) [inline src/lib/factories.tsx]: don't we want to have `mergeStyles` function that would encapsulate this logic? Similar semantics is expressed in the `mergeThemes` file:

```js
// mergeComponentStyles() {
...
return _.merge(callable(originalTarget)(styleParam), callable(originalSource)(styleParam))
```

maybe we could encapsulate and reuse this logic in the following way:

```ts
mergeStyles(target: ComponentSlotStyle, ...styles: ComponentSlotStyle[]) {
  ...
}
```

**Review by kuzhelov — APPROVED** [review]
it would be great if we'll be able to encapsulate this logic for merging styles, to prevent similar mistakes from happening in future

**Review by miroslavstastny — APPROVED** [review]

File: src/lib/factories.tsx (hunk 3 above)
Comment (mnajdova) [reply src/lib/factories.tsx]: Agreed, will encapsulate this logic.

Comment (mnajdova) [reply src/lib/factories.tsx]: Introduced, please review again.

File: test/specs/lib/factories-test.tsx (hunk 2 above)
Comment (mnajdova) [reply test/specs/lib/factories-test.tsx:309]: I would rather leave this tests the same as the previous ones for consistency, as the only difference is changing the objects to functions.
