### PR TITLE
fix(Popup): fix broken background with pointing and FocusTrap

### LINKED ISSUE #1679: Teams theme: Popup pointing styles still broken with focus trap
## Bug Report

After fix in #1433 Popup pointing with focus trap is still broken:

image

### Version
0.34.1

### Testcase
https://codesandbox.io/s/popup-pointing-with-focustrap-broken-styles-8kenr

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1679.

## Problem

In `master` we have already resolved this issue by #1565, however we need to provide a fix without breaking changes for now.

### Before

image

### After

image

#### Test snippet

```tsx
import * as React from 'react'
import { Button, Flex, Popup, popupFocusTrapBehavior } from '@stardust-ui/react'

const plainContentStyle = {
  zIndex: 1000,
  padding: 5,
}

const PopupExample = () => (
  <Flex vAlign='center' space='between' styles={{ padding: '50px', height: '500px', backgroundColor: 'orange' }}>
    <Popup content="Hello from popup!" pointing open accessibility={popupFocusTrapBehavior}>
      <Button icon="expand"/>
    </Popup>

    <Popup open content={<p style={plainContentStyle}>Plain popup content rendered 'as is'.</p>}>
      <Button icon="expand" content="Popup with plain content"/>
    </Popup>
    <Popup open accessibility={popupFocusTrapBehavior}
           content={<p style={plainContentStyle}>Plain popup content rendered 'as is'.</p>}>
      <Button icon="expand" content="Popup with plain content"/>
    </Popup>

    <Popup
      open
      content={{ content: <p style={plainContentStyle}>Popup content rendered in wrapper.</p> }}
    >
      <Button icon="expand" content="Popup with wrapped content"/>
    </Popup>
  </Flex>
)

export default PopupExample
```

### CODE REVIEW

File: packages/react/src/themes/teams/components/Popup/popupStyles.ts [hunk 1]
```diff
@@ -1,16 +1,34 @@
...
     zIndex: v.zIndex,
     position: 'absolute',
     textAlign: 'left',
-    color: v.contentColor,
-    background: v.contentBackgroundColor,
+
+    /*
+     * This fix handles all cases with wrapped focus trap.
+     */
+    ...(React.isValidElement(p.content) && {
```
Comment (kuzhelov) [inline packages/react/src/themes/teams/components/Popup/popupStyles.ts]: actually, this should also apply in case if render function is provided as an argument :( as in that case slot component will be also replaced. So, I think that we may just check that this is not an object or primitive

**Review by kuzhelov — APPROVED** [review]

**Comment by layershifter** [comment]
Adjusted to handle `render()` callback cases:

```tsx
    <Popup open trigger={<Button icon="expand"/>} content={render => render(
      {},
      (ComponentType, props) => (
        <p style={{ zIndex: 1000, padding: 5 }}>Plain popup content rendered 'as is'.</p>
      ),
    )}/>
    <Popup open trigger={<Button icon="expand"/>} pointing content={render => render(
      {},
      (ComponentType, props) => (
        <div {...props} style={{ zIndex: 1000, padding: 5}}>
          Plain popup content rendered 'as is'.
        </div>
      ),
    )}/>
```

image
