### PR TITLE
fix(factories): add types to createShorthandFactory() methods

### LINKED ISSUE #1865: Typings: Factories are not properly typed
### Steps
1. Use any `.create()` method:
```tsx
{Avatar.create(Symbol("foo"), "FOO", "BAR")}
```
https://codesandbox.io/s/stardust-ui-example-0tkkx

Issue exists because all our `.create()` functions are typed as `Function` 💥 

image

### Expected Result
Types error.

### Actual Result
No type error 💣 

### Version
0.37.0

### PR DESCRIPTION
**Pull request by lucivpav**
Fixes #1865 

The new type is
```tsx
export type ShorthandFactory = (
  value: ShorthandValue<UIComponentProps>,
  options?: CreateShorthandOptions,
) => React.ReactElement | null | undefined
```

## Won't compile
```tsx
{Avatar.create(Symbol("foo"), "FOO", "BAR")}
{Avatar.create(Symbol("foo"))}
```

## Will compile
```tsx
avatar?: ShorthandValue<AvatarProps> = ...
{Avatar.create(avatar}, {defaultProps: {...}, overrideProps: {...}}
{Avatar.create(avatar}}
```

And this will unfortunately also compile
```tsx
button?: ShorthandValue<ButtonProps> = ...
{Avatar.create(button}}
```

### CODE REVIEW

File: packages/react/src/components/Tree/Tree.tsx [hunk 1]
```diff
@@ -263,7 +263,7 @@ class Tree extends AutoControlledComponent<WithAsProp<TreeProps>, TreeState> {
           const isSubtree = hasSubtree(item)
           const isSubtreeOpen = isSubtree && this.isActiveItem(item['id'])
 
-          const renderedItem = TreeItem.create(item, {
+          const renderedItem: any = TreeItem.create(item, {
```
Comment (lucivpav) [inline packages/react/src/components/Tree/Tree.tsx]: Without `any`, a strange TS error shows up: 
```
Type 'ShorthandValue<TreeItemProps & { kind?: never; }>' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>[]'.
  Type 'string' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>[]'.ts(2322)
```
I didn't find a way to resolve it

File: packages/react/src/lib/factories.ts [hunk 2]
```diff
@@ -10,6 +10,7 @@ import {
   ShorthandRenderer,
 } from '../types'
 import { mergeStyles } from './mergeThemes'
+import { UIComponentProps } from '.'
```
Comment (layershifter) [inline packages/react/src/lib/factories.ts]: Ouch, circular reference

```suggestion
import { UIComponentProps } from './commonPropInterfaces'
```

File: packages/react/src/lib/factories.ts [hunk 3]
```diff
@@ -91,6 +92,10 @@ type CreateShorthandFactoryConfigInner<TPropName = string> = {
   mappedArrayProp?: TPropName
 }
 export type CreateShorthandFactoryConfig = CreateShorthandFactoryConfigInner
+export type CreateShorthandFactoryResult = (
```
Comment (layershifter) [inline packages/react/src/lib/factories.ts]: Actually, the result of `createShorthandFactory` is `ShorthandFactory`

```suggestion
export type ShorthandFactory = (
```

File: packages/react/src/lib/factories.ts [hunk 4]
```diff
@@ -91,6 +92,10 @@ type CreateShorthandFactoryConfigInner<TPropName = string> = {
...
+  a: ShorthandValue<UIComponentProps>,
```
Comment (layershifter) [inline packages/react/src/lib/factories.ts]:
```suggestion
  value: ShorthandValue<UIComponentProps>,
```

File: packages/react/src/lib/factories.ts [hunk 5]
```diff
@@ -91,6 +92,10 @@ type CreateShorthandFactoryConfigInner<TPropName = string> = {
...
+  b: CreateShorthandOptions,
```
Comment (layershifter) [inline packages/react/src/lib/factories.ts]:
```suggestion
  options?: CreateShorthandOptions,
```

This param is also optional

File: packages/react/src/lib/factories.ts (hunk 4 above)
Comment (layershifter) [reply packages/react/src/lib/factories.ts]:
```suggestion
  a: ShorthandValue<P>,
```

Actually, let's make it generic and accept component props there. Hope that it will work

File: docs/src/components/ColorSchemes.tsx [hunk 6]
```diff
@@ -57,7 +57,7 @@ const ColorSchemes = createComponent<ColorVariantsProps>({
     return (
       <div className={classes.root}>
         <Grid columns={columns}>
-          {headers && headers.map(header => Header.create(header))}
+          {headers && headers.map(header => Header.create(header, {}))}
```
Comment (layershifter) [inline docs/src/components/ColorSchemes.tsx]:
```suggestion
          {headers && headers.map(header => Header.create(header))}
```

Second param should be optional

File: packages/react/src/components/Dropdown/Dropdown.tsx [hunk 7]
```diff
@@ -743,8 +743,10 @@ class Dropdown extends AutoControlledComponent<WithAsProp<DropdownProps>, Dropdo
       !loading &&
         items.length === 0 &&
         ListItem.create(noResultsMessage, {
-          key: 'no-results-message',
-          styles: styles.noResultsMessage,
+          defaultProps: {
+            key: 'no-results-message',
+            styles: styles.noResultsMessage,
+          },
```
Comment (layershifter) [inline packages/react/src/components/Dropdown/Dropdown.tsx:749]: ❤️

File: packages/react/src/components/Tree/Tree.tsx (hunk 1 above)
Comment (layershifter) [reply packages/react/src/components/Tree/Tree.tsx]: Looks like TS bug, I suggest to move any to other place instead

```tsx
const renderItems = (items: ShorthandCollection<TreeItemProps>) => {
      return items.reduce<React.ReactElement[]>(
        (renderedItems, item): React.ReactElement[] => {
          const itemForRender = itemsForRender[item['id']]
          const { elementRef, ...restItemForRender } = itemForRender
          const isSubtree = hasSubtree(item)
          const isSubtreeOpen = isSubtree && this.isActiveItem(item['id'])

          const renderedItem = TreeItem.create(item, {
            defaultProps: {
              className: Tree.slotClassNames.item,
              open: isSubtreeOpen,
              renderItemTitle,
              key: item['id'],
              ...restItemForRender,
            },
            overrideProps: this.handleTreeItemOverrides,
          })

          // Only need refs of the items that spawn subtrees, when they need to be focused
          // by any of their children, using Arrow Left.
          const finalRenderedItem = isSubtree ? (
            <Ref key={item['id']} innerRef={elementRef}>
              {renderedItem}
            </Ref>
          ) : (
            renderedItem
          )

          return [
            ...renderedItems,
            finalRenderedItem,
            ...[isSubtreeOpen ? renderItems(item['items']) : []] as any,
          ]
        },
        [],
      )
    }
```

File: packages/react/src/lib/factories.ts [hunk 8]
```diff
@@ -91,6 +92,10 @@ type CreateShorthandFactoryConfigInner<TPropName = string> = {
...
+) => React.ReactElement<Props> | null | undefined
```
Comment (layershifter) [inline packages/react/src/lib/factories.ts]:
```suggestion
) => React.ReactElement | null | undefined
```

It defaults to `any`

File: packages/react/src/lib/factories.ts (hunk 4 above)
Comment (lucivpav) [reply packages/react/src/lib/factories.ts]: Yes it works

File: packages/react/src/components/Menu/MenuItem.tsx [hunk 9]
```diff
@@ -214,7 +215,8 @@ class MenuItem extends AutoControlledComponent<WithAsProp<MenuItemProps>, MenuIt
     } = this.props
     const { menuOpen } = this.state
 
-    const indicatorWithDefaults = indicator === undefined ? {} : indicator
+    const defaultIndicator = { name: vertical ? 'stardust-arrow-end' : 'stardust-arrow-down' }
+    const indicatorWithDefaults = indicator === undefined ? defaultIndicator : indicator
```
Comment (layershifter) [inline packages/react/src/components/Menu/MenuItem.tsx:219]: Are these changes required? Can we revert them?

File: packages/react/src/components/Accordion/AccordionTitle.tsx [hunk 10]
```diff
@@ -106,7 +107,8 @@ class AccordionTitle extends UIComponent<WithAsProp<AccordionTitleProps>, any> {
 
   renderComponent({ ElementType, classes, unhandledProps, styles, accessibility }) {
     const { contentRef, children, content, indicator, active } = this.props
-    const indicatorWithDefaults = indicator === undefined ? {} : indicator
+    const defaultIndicator = { name: active ? 'stardust-arrow-down' : 'stardust-arrow-end' }
+    const indicatorWithDefaults = indicator === undefined ? defaultIndicator : indicator
```
Comment (layershifter) [inline packages/react/src/components/Accordion/AccordionTitle.tsx:111]: https://github.com/stardust-ui/react/pull/1875/files#diff-d5390340926344f30b1c6712c4e548c7R219

File: packages/react/src/components/Menu/MenuItem.tsx (hunk 9 above)
Comment (lucivpav) [reply packages/react/src/components/Menu/MenuItem.tsx:219]: It is required, because Type `{}` is not assignable to type `Props<IconProps>`.

**Review by layershifter — APPROVED** [review]

**Comment by lucivpav** [comment]
Another PR: `CreateShorthandOptions` should be typed as `CreateShorthandOptions<P>`
