### PR TITLE
fix(Toolbar): focus first item each time a focused element is hidden

### LINKED ISSUE #2175: Overflow menu in toolbar - When "..." more button disappear user is not able navigate back to toolbar
### Steps
1. Make toolbar menu overflow with some narrow sceen 
2. resize the window with Win key + down arrow key
2. Navigate by arrow key to the more button "..." and focus stays on the button
3. restore the window to big one with win key + up arrow key
4. try to navigate back to the toolbar

### Expected Result
user is able to navigate back to the toolbar even "..." button get disappeared

### Actual Result
user is not able navigate back to the toolbar at all...

### PR DESCRIPTION
**Pull request by silviuaavram**
Fixes https://github.com/microsoft/fluent-ui-react/issues/2175

### CODE REVIEW

File: packages/react/src/components/Toolbar/Toolbar.tsx [hunk 1]
```diff
@@ -184,6 +185,15 @@ class Toolbar extends UIComponent<WithAsProp<ToolbarProps>> {
       return
     }
 
+    if (
+      this.context.target.activeElement === el ||
+      el.contains(this.context.target.activeElement)
+    ) {
+      if (this.containerRef.current) {
+        this.containerRef.current.querySelector('[tabindex]')
```
Comment (layershifter) [inline packages/react/src/components/Toolbar/Toolbar.tsx]: Does it really work? I don't see any logic there 🤔 

Let's also add somehow E2E test for this to avoid issues in future

Comment (jurokapsiar) [inline packages/react/src/components/Toolbar/Toolbar.tsx]: could you pls check if `getFirstFocusable` from packages\react-bindings\src\FocusZone\focusUtilities.ts would work?

Comment (silviuaavram) [reply packages/react/src/components/Toolbar/Toolbar.tsx]: oups

Comment (silviuavram) [reply packages/react/src/components/Toolbar/Toolbar.tsx]: What do you think it's better?
```js
        const firstFocusableItem = getFirstFocusable(
          this.containerRef.current,
          this.containerRef.current.firstElementChild,
        )
```
or
```js
        const firstFocusableItem = getFirstFocusable(
          this.containerRef.current,
          this.containerRef.current,
        )
````
Both seem to work in this case.

File: e2e/tests/toolbarMenuOverflowWrapped-test.ts [hunk 2]
```diff
@@ -0,0 +1,58 @@
+import { selectors, itemsCount } from './toolbarMenuOverflowWrapped-example'
+
+const toolbarItem = (index: number) => `.${selectors.toolbarItem}:nth-child(${index + 1})`
+const toolbarItemWrapped = (index: number) =>
+  `.${selectors.toolbarItemWrapper}:nth-child(${index + 1}) .${selectors.toolbarItem}`
+const toolbar = `.${selectors.toolbar}`
+
+describe('Toolbar menu overflow with wrapped first item', () => {
```
Comment (kolaps33) [inline e2e/tests/toolbarMenuOverflowWrapped-test.ts:8]: just small observation we have the same naming for the describe as well in the "toolbarMenuOverflow-test.ts"

**Review by kolaps33 — APPROVED** [review]
