### PR TITLE
fix(Carousel): do not render hidden carousel items

### LINKED ISSUE #2272: Carousel with actionable elements is not accessible
### Steps
Related PR: https://github.com/microsoft/fluent-ui-react/pull/2271
1.
Navigate into the branch 
mituron/carousel-focusable-elements
where I been adding actionable elements inside the carousel. 
2.1 
No reader is required.
Navigate by TAB key into the first carousel item and keep tabbing...
Expected: user navigate to the tab below carousel item
Actual: user navigate to the next actionable element on next carousel item

2.2 
JAWS is on. 
Switch to the second carousel item and navigate with Virtual cursor. 
Expected: toolbar is navigable by virtual cursor
Actual: toolbar is not navigable

2.3
VoiceOver is on. 
Switch to the last carousel item. 
Navigate above the carousel. 
Press TAB key go into the carousel. 
Expected: item carousel is focused
Actual: button on first carousel item get focused

Comment:
Looks like with high probability all bugs are caused that not visible items did not get property: display: none

### PR DESCRIPTION
**Pull request by mnajdova**
Fixes https://github.com/microsoft/fluent-ui-react/issues/2272

### CODE REVIEW

File: packages/react/src/components/Carousel/Carousel.tsx [hunk 1]
```diff
@@ -270,14 +273,23 @@ class Carousel extends AutoControlledComponent<WithAsProp<CarouselProps>, Carous
...
+            this.itemRefs.push(itemRef)
+            const active = activeIndex === index
+            const slideToNext = prevActiveIndex < activeIndex
+            return (
+              <Animation
+                mountOnEnter
+                unmountOnExit
+                visible={active}
+                // TODO figure out which animations should be used and add required names in the theme
+                name={active ? slideToNext ? 'slideLeftEnterMedium' : 'slideRightEnterMedium' : slideToNext ? 'slideLeftExitMedium' : 'slideRightExitMedium'}
```
Comment (mnajdova) [inline packages/react/src/components/Carousel/Carousel.tsx]: @codepretty do you know which animations we should use for the carousel slides?

File: packages/react/src/components/Carousel/Carousel.tsx [hunk 2]
```diff
@@ -270,14 +273,23 @@ class Carousel extends AutoControlledComponent<WithAsProp<CarouselProps>, Carous
...
+            this.itemRefs.push(itemRef)
+            const active = activeIndex === index
+            const slideToNext = prevActiveIndex < activeIndex
+            return (
+              <Animation
+                mountOnEnter
+                unmountOnExit
+                visible={active}
+                // TODO figure out which animations should be used and add required names in the theme
+                name={active ? slideToNext ? 'carousel-slide-to-next-enter' : 'carousel-slide-to-previous-enter' : slideToNext ? 'carousel-slide-to-next-exit' : 'carousel-slide-to-previous-exit'}
```
Comment (mnajdova) [inline packages/react/src/components/Carousel/Carousel.tsx]: @codepretty @bhamlefty can you suggest which animations we should use on the carousel for sliding to next/prev  items?

File: packages/react/src/themes/teams/animations/slide.ts [hunk 3]
```diff
@@ -188,7 +188,7 @@ const slideAnimations = {
     fillMode: 'forwards',
   },
   // Slides object in from left to right
-  SlideRightEnterMedium: {
+  slideRightEnterMedium: {
```
Comment (mnajdova) [inline packages/react/src/themes/teams/animations/slide.ts:191]: fixed based on naming convention

File: packages/react-bindings/src/styles/convertCssTimeToNumber.ts [hunk 4]
```diff
@@ -0,0 +1,18 @@
+import * as _ from 'lodash'
+
+const convertCssTimeToNumber = (time: string): number => {
```
Comment (miroslavstastny) [inline packages/react-bindings/src/styles/convertCssTimeToNumber.ts]: Would this be worth a UT?

File: packages/react-bindings/src/styles/calculateAnimationTimeout.ts [hunk 5]
```diff
@@ -0,0 +1,10 @@
+import convertCssTimeToNumber from './convertCssTimeToNumber'
+import * as _ from 'lodash'
+
+const calculateAnimationTimeout = (duration: string, delay: string | undefined): number => {
+  if (_.isNil(duration) || duration === 'inherit' || duration === 'initial') return 0
+  if (!_.isNil(delay) && (delay === 'inherit' || delay === 'initial')) return 0
```
Comment (layershifter) [inline packages/react-bindings/src/styles/calculateAnimationTimeout.ts]: If it's under `react-bindings` I would like to avoid dependency on Lodash

Comment (layershifter) [inline packages/react-bindings/src/styles/calculateAnimationTimeout.ts]:
```suggestion
  if (delay === 'inherit' || delay === 'initial') return 0
```

I don't think that `isNil()` is a real part of condition there

File: packages/react-bindings/src/styles/calculateAnimationTimeout.ts [hunk 6]
```diff
@@ -0,0 +1,10 @@
+import convertCssTimeToNumber from './convertCssTimeToNumber'
+import * as _ from 'lodash'
+
+const calculateAnimationTimeout = (duration: string, delay: string | undefined): number => {
```
Comment (silviuaavram) [inline packages/react-bindings/src/styles/calculateAnimationTimeout.ts]: isn't `delay: string | undefined` equivalent with `delay?: string` ?

File: packages/react-bindings/src/styles/convertCssTimeToNumber.ts [hunk 7]
```diff
@@ -0,0 +1,20 @@
...
+  if (_.isNil(time) || time === 'initial' || time === 'inherit') {
+    return 0
+  }
+
+  if (!_.endsWith(time, 'ms') && !_.endsWith(time, 's')) {
```
Comment (silviuaavram) [inline packages/react-bindings/src/styles/convertCssTimeToNumber.ts:8]: probably better to read if conditions are positive.

```suggestion
  if (_.endsWith(time, 'ms') || _.endsWith(time, 's')) {
```

File: packages/react-bindings/test/styles/convertCssTimeToNumber-test.ts [hunk 8]
```diff
@@ -0,0 +1,25 @@
...
+  test('converts other valid css values to 0', () => {
+    expect(calculateAnimationTimeout('initial', '200ms')).toEqual(0)
+    expect(calculateAnimationTimeout('inherit', '400ms')).toEqual(0)
+  })
+
+  test('converts invalid css values to 0', () => {
+    expect(calculateAnimationTimeout('intial', undefined)).toEqual(0)
+  })
+
+  test('returns the duration if delay is not set other valid css values to 0', () => {
```
Comment (silviuaavram) [inline packages/react-bindings/test/styles/convertCssTimeToNumber-test.ts]: I don't understand what is after `set`.

File: packages/react-bindings/src/styles/convertCssTimeToNumber.ts (hunk 7 above)
Comment (mnajdova) [reply packages/react-bindings/src/styles/convertCssTimeToNumber.ts:8]: But it should be  `if (!(_.endsWith(time, 'ms') || _.endsWith(time, 's'))) {` in that case

Comment (silviuaavram) [reply packages/react-bindings/src/styles/convertCssTimeToNumber.ts:8]: yeah, sorry about that!

File: packages/react-bindings/src/styles/calculateAnimationTimeout.ts (hunk 5 above)
Comment (mnajdova) [reply packages/react-bindings/src/styles/calculateAnimationTimeout.ts]: We shouldn't have added it as dependency if we don't want it. I am already using `_.isNil`, `_.endsWith` and `_.toNumber`... If we decide to remove it from the package, we can refactor all files that use lodash

File: packages/react-bindings/src/styles/calculateAnimationTimeout.ts (hunk 6 above)
Comment (layershifter) [reply packages/react-bindings/src/styles/calculateAnimationTimeout.ts]: No, there are not equivalent

```
(delay?: string) === (delay: string | undefined = undefined)
```

https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABAQwBTDnA-ALkQZygCcYwBzASkQG9EBfAKAbQudQHIM53WHRJYCRACN0mPIRLlEAH0TgAJgFNgpJQqq1Go1qM6YeDIA

File: packages/react-bindings/test/styles/convertCssTimeToNumber-test.ts [hunk 9]
```diff
@@ -0,0 +1,25 @@
+import { unstable_calculateAnimationTimeout as calculateAnimationTimeout } from '@fluentui/react-bindings'
+
+describe('convertCssTimeToNumber', () => {
+  test('converts ms values to number', () => {
+    expect(calculateAnimationTimeout('200ms', '300ms')).toEqual(500)
+  })
+
+  test('converts s values to number', () => {
```
Comment (layershifter) [inline packages/react-bindings/test/styles/convertCssTimeToNumber-test.ts]:
```suggestion
  test('converts "s" values to number', () => {
```

File: packages/react-bindings/src/styles/calculateAnimationTimeout.ts [hunk 10]
```diff
@@ -0,0 +1,10 @@
+import convertCssTimeToNumber from './convertCssTimeToNumber'
+import * as _ from 'lodash'
+
+const calculateAnimationTimeout = (duration: string, delay?: string): number => {
+  if (_.isNil(duration) || duration === 'inherit' || duration === 'initial') return 0
```
Comment (layershifter) [inline packages/react-bindings/src/styles/calculateAnimationTimeout.ts:5]: According to types `duration` can be only string

A.  Update typings

```tsx
const calculateAnimationTimeout = (duration: string | undefined, delay?: string): number => {
```

B. Remove `_.isNil()`

```suggestion
  if (duration === 'inherit' || duration === 'initial') return 0
```

File: packages/react-bindings/test/styles/convertCssTimeToNumber-test.ts [hunk 11]
```diff
@@ -0,0 +1,25 @@
...
+    expect(calculateAnimationTimeout('20s', '2s')).toEqual(22000)
+  })
+
+  test('converts other valid css values to 0', () => {
+    expect(calculateAnimationTimeout('initial', '200ms')).toEqual(0)
+    expect(calculateAnimationTimeout('inherit', '400ms')).toEqual(0)
```
Comment (layershifter) [inline packages/react-bindings/test/styles/convertCssTimeToNumber-test.ts:14]: Is this valid? Should it be `400ms`?

File: packages/react/src/components/Carousel/Carousel.tsx [hunk 12]
```diff
@@ -251,18 +262,33 @@ class Carousel extends AutoControlledComponent<WithAsProp<CarouselProps>, Carous
     }
   }
 
-  renderContent = (accessibility, styles, unhandledProps) => {
-    const { ariaRoleDescription, getItemPositionText, items } = this.props
-    const { activeIndex, itemIds } = this.state
+  overrideItemProps = predefinedProps => ({
```
Comment (layershifter) [inline packages/react/src/components/Carousel/Carousel.tsx:268]: Does this means that we will rerender the whole `Carousel` base on focus event in `CarouselItem`? 💣

File: packages/react/src/components/Carousel/Carousel.tsx [hunk 13]
```diff
@@ -273,19 +299,49 @@ class Carousel extends AutoControlledComponent<WithAsProp<CarouselProps>, Carous
...
               return (
-                <Ref key={item['key'] || index} innerRef={itemRef}>
-                  {CarouselItem.create(item, {
-                    defaultProps: () => ({
-                      active: activeIndex === index,
-                      id: itemIds[index],
-                      navigation: !!this.props.navigation,
-                      ...(getItemPositionText && {
-                        itemPositionText: getItemPositionText(index, items.length),
+                <Animation
```
Comment (layershifter) [inline packages/react/src/components/Carousel/Carousel.tsx:321]: Just wondering why this thing is not a part of `CarouselItem`?

File: packages/react/src/themes/teams/components/Carousel/carouselStyles.ts [hunk 14]
```diff
@@ -10,18 +10,22 @@ const carouselStyles: ComponentSlotStylesPrepared<
...
     display: 'inline-block',
   }),
-  itemsContainerWrapper: ({ variables: v }): ICSSInJSStyle => ({
+  itemsContainerWrapper: ({ variables: v, props: p }): ICSSInJSStyle => ({
     display: 'flex',
     width: pxToRem(v.width),
     overflowX: 'hidden',
+    border: '1px solid transparent',
+
+    ...(p.shouldFocusContainer && {
```
Comment (layershifter) [inline packages/react/src/themes/teams/components/Carousel/carouselStyles.ts]: Should we use there `focus-visible`?

File: packages/react-bindings/test/styles/convertCssTimeToNumber-test.ts (hunk 11 above)
Comment (mnajdova) [reply packages/react-bindings/test/styles/convertCssTimeToNumber-test.ts:14]: If there is `initial` or `inherit`, we should return 0, as we cannot calculate it, and the user should provide the timeout value, or we will remove/add the element immediately.

File: packages/react/src/components/Carousel/Carousel.tsx (hunk 12 above)
Comment (mnajdova) [reply packages/react/src/components/Carousel/Carousel.tsx:268]: Well if we could have used `focus-within` we could have avoid it.. Do you have alternative idea?

File: packages/react-bindings/src/styles/calculateAnimationTimeout.ts (hunk 6 above)
Comment (silviuaavram) [reply packages/react-bindings/src/styles/calculateAnimationTimeout.ts]: I guess my question was more like "why would I ever pass explicitly `undefined` as the last parameter" of a function?

File: packages/react/src/components/Carousel/Carousel.tsx (hunk 13 above)
Comment (mnajdova) [reply packages/react/src/components/Carousel/Carousel.tsx:321]: Some of the things here are specific to the Carousel, like whether we are sliding to next/prev, whether it is initialMounting etc. We would need to add more props to the CarouselItem, for handling these. I'd rather keep this here and keep the CarouselItem be responsible only for the things it should know about

File: packages/react/src/themes/teams/components/Carousel/carouselStyles.ts (hunk 14 above)
Comment (mnajdova) [reply packages/react/src/themes/teams/components/Carousel/carouselStyles.ts]: This is a valid point, we should not have this border when it is coming from click, but unfortunately we have to use `isFromKeyboard` :(

File: packages/react/src/components/Carousel/Carousel.tsx (hunk 12 above)
Comment (layershifter) [reply packages/react/src/components/Carousel/Carousel.tsx:268]: DOM attributes 💣 

Let's go with the current approach now

File: packages/react/src/components/Carousel/Carousel.tsx (hunk 13 above)
Comment (layershifter) [reply packages/react/src/components/Carousel/Carousel.tsx:321]: Because if we will decide to have there children API there will be animations only for shorthands...

Comment (mnajdova) [reply packages/react/src/components/Carousel/Carousel.tsx:321]: Still not sure that it is a good way of handling it, as I would rather wrap anything with Animations, than adding Animation in any component, just because it may be animated somewhere... We can iterate when we will add children and consider what is the best option that would work in both cases.

File: packages/react-bindings/src/styles/calculateAnimationTimeout.ts (hunk 6 above)
Comment (mnajdova) [reply packages/react-bindings/src/styles/calculateAnimationTimeout.ts]: Because we are passing props here and the prop can be undefined... Anyway, I agree that for the last param it can be optional, for the other ones we need `string | undefined`

**Review by layershifter — APPROVED** [review]

**Review by silviuaavram — APPROVED** [review]
