### PR TITLE
fix(shorthand): prop type

### LINKED ISSUE #676: Function is not a valid shorthand
### Steps
```jsx
<Menu
  items={[
    render => render(3, (Component, props) => <Component {...props} />)
  ]}
/>
```

### Expected Result
Custom render function is used (as described in #355), no warning

### Actual Result
Custom render function is used as expected,
There is warning in console: 💣
```
Warning: Failed prop type: Invalid prop `items[0]` supplied to `Menu`.
    in Menu (created by App)
    in App
    in ThemeProvider (created by FelaTheme)
    in Provider (created by FelaTheme)
    in FelaTheme (created by ProviderConsumer)
    in ProviderConsumer (created by Provider)
    in Provider
```

### Version
0.15.0

### Testcase
https://codesandbox.io/s/6jmvkyyz9w

### PR DESCRIPTION
**Pull request by kuzhelov**
## TODO 
- [x] update CHANGELOG

Fixes #676.

### CODE REVIEW

File: src/lib/customPropTypes.tsx [hunk 1]
```diff
@@ -374,11 +374,11 @@ export const wrapperShorthand = PropTypes.oneOfType([
 
 /**
  * Item shorthand is a description of a component that can be a literal,
- * a props object, or an element.
+ * a props object, an element or render function.
```
Comment (layershifter) [inline src/lib/customPropTypes.tsx]:
```suggestion
 * a props object, an element or a render function.
```

nit: missing `a` 😺

**Review by layershifter — APPROVED** [review]
