### PR TITLE
docs(fix): navigation links

### LINKED ISSUE #1851: Relative navigation link doesn't work properly when opening new tab
### Steps
Go to the stardust FAQ page
Open navigation link "Does Stardust support mobile?" in new tab

### Expected Result
Link is open properly in new tab

### Actual Result
Link doesn't open correct page. 
Issue is that link doesn't point to correct url. 
Please see screnshot:
image

### Version
x.y.z

### Testcase
[Fork, update, and replace this sandbox to show the bug]:
https://codesandbox.io/s/stardust-ui-example-8ismt

### PR DESCRIPTION
**Pull request by lucivpav**
This fixes #1851
### Before
image
image

### After
image
image

### CODE REVIEW

**Comment by lucivpav** [comment]
Any suggestion on how to test this, so the links won't break again in the future?

File: docs/src/components/DocsLayout.tsx [hunk 1]
```diff
@@ -59,10 +59,7 @@ class DocsLayout extends React.Component<any, any> {
     // Anchor links has issues with <base>
     // https://stackoverflow.com/questions/8108836/make-anchor-links-refer-to-the-current-page-when-using-base
     document.querySelectorAll('a.anchor-link').forEach(link => {
-      link.addEventListener('click', e => {
-        e.preventDefault()
-        document.location.hash = link.getAttribute('href')
-      })
+      link.setAttribute('href', document.location.href + link.getAttribute('href'))
```
Comment (silviuaavram) [inline docs/src/components/DocsLayout.tsx]: nit: ``link.setAttribute('href', `${document.location.href}${link.getAttribute('href')}`)``

File: docs/src/utils/helpers.tsx [hunk 2]
```diff
@@ -10,11 +10,7 @@ export const link = (content: string, href: string) => {
 
   if (isAnchor || isExternal) {
     return (
-      <a
-        className={isAnchor ? 'anchor-link' : undefined}
-        href={href}
-        {...(isExternal && { target: 'blank' })}
-      >
+      <a href={isAnchor ? location.pathname + href : href} {...(isExternal && { target: 'blank' })}>
```
Comment (silviuaavram) [inline docs/src/utils/helpers.tsx]: nit

``<a href={`${isAnchor ? location.pathname : ''}${href}`} {...(isExternal && { target: 'blank' })}>``

**Review by silviuaavram — APPROVED** [review]
