### PR TITLE
fix(ComponentExample|ComponentSourceManager): fix initial state of knobs, fix undeletable code

### LINKED ISSUE #668: Docsite: initial knobs state ignored
### Steps
In Docsite check an example with knobs, (ItemLayout/Truncate).

### Expected Result
The example behaves according to knobs

### Actual Result
Knobs state is ignored until it is touched 💣
In the screenshot below, both header and content text should be truncated but knobs attribute passed to the example is empty object. 
image

### Version
0.15.0

### Testcase
https://stardust-ui.github.io/react/components/item-layout#variations-truncate

### LINKED ISSUE #719: Docs: unable to completely remove example's code
### Steps
1. Go to any example, https://stardust-ui.github.io/react/components/button#types-button
2. Click "Try it"
3. Select all lines in a source code and try to remove them with `Delete` or `Backspace` key'

### Expected Result
Code was cleared.

### Actual Result
docs-delete

### Version
Master

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #719.
Fixes #668.

---

- rename `theme-context.tsx` → `ThemeContext.tsx`
- switch from old context API in `ComponentExample`

### CODE REVIEW

File: docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx [hunk 1]
```diff
@@ -60,44 +61,23 @@ class ComponentExample extends React.Component<ComponentExampleProps, ComponentE
...
-    description: PropTypes.node,
-    examplePath: PropTypes.string.isRequired,
-    history: PropTypes.object.isRequired,
-    location: PropTypes.object.isRequired,
-    match: PropTypes.object.isRequired,
-    title: PropTypes.node,
-    themeName: PropTypes.string,
-  }
-
-  componentWillMount() {
```
Comment (layershifter) [inline docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx:92]: https://reactjs.org/docs/react-component.html#unsafe_componentwillmount
This method is deprecated, switched to `constructor`

**Review by miroslavstastny — APPROVED** [review]
