### PR TITLE
fix(ListItem): end media in Teams theme breaks ButtonGroup styles

### LINKED ISSUE #1287: ButtonGroup style breaking when inside endMedia of ListItem
## Bug Report
ButtonGroup style breaking when inside endMedia of ListItem.

### Expected Result
The buttons inside ButtonGroup should stay inline

### Actual Result
The buttons inside ButtonGroups are positioned in a column
onHover

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/embed/0qp5yvj4ql

### PR DESCRIPTION
**Pull request by mnajdova**
Fix https://github.com/stardust-ui/react/issues/1287

ButtonGroup style were broken when inside endMedia of ListItem.

**Before:**
image

**After:**
image

### CODE REVIEW

File: packages/react/src/themes/teams/components/List/listItemStyles.ts [hunk 1]
```diff
@@ -100,6 +100,7 @@ const listItemStyles: ComponentSlotStylesInput<ListItemPropsAndState, any> = {
   }),
   endMedia: ({ props: p }) => ({
     ...(p.selectable && { display: 'none' }),
+    flexShrink: 0,
```
Comment (bmdalex) [inline packages/react/src/themes/teams/components/List/listItemStyles.ts:103]: I'm still not sure if the List behaves correctly... Pls. take a look at this screenshot:

Screen Recording 2019-06-04 at 14 21 49

here is the example I used:

```jsx
import * as React from 'react'
import * as _ from 'lodash'
import { List, Button } from '@stardust-ui/react'

const items = [
  {
    key: 'ftp',
    endMedia: (
      <Button.Group
        buttons={_.times(20).map(i => ({
          key: 'accept' + i,
          icon: 'accept',
          iconOnly: true,
          text: true,
        }))}
      />
    ),
    content:
      'Use the online FTP application to input the multi-byte application!Use the online FTP application to input the multi-byte application!',
  },
]

const ListExample = () => <List items={items} selectable />

export default ListExample
```

Comment (mnajdova) [reply packages/react/src/themes/teams/components/List/listItemStyles.ts:103]: The `media` and `endMedia` should have width as the content inside them. The `content` between them is suppose to grow in order to fill the list item. If we follow this, I think your example is still correct.

**Review by kuzhelov — APPROVED** [review]
