### PR TITLE
fix: remove 'skipLibCheck' flag requirement from client's projects

### LINKED ISSUE #276: Stardust is unconsumable for TS client project with no --skipLibCheck flag
### Steps
- create test app project: `create-react-app --scripts-version=react-scripts-ts`
- add Stardust as a dependency: `yarn add @stardust-ui/react`
- reference some components from Stardust in `App.tsx`
- try to build the project

### Expected Result
Project builds successfully.

### Actual Result
Project fails to build 💣

### Version
0.6.0

### PR DESCRIPTION
**Pull request by kuzhelov**
# TODO
- [x] update CHANGELOG

-----------

This PR serves the main goal to eliminate requirement of using `skipLibCheck` TS compiler flag in client's TS projects (fixes #276). Detailed overview is provided below.

### Problem
`skipLibCheck` was a mandatory flag for client's TS projects to consume Stardust. 

### Solution
With `typescript` package has been upgraded to 3.1.* this issue is fixed (fix for the related one https://github.com/Microsoft/TypeScript/issues/27136 has resolved problem for us). To prevent potential breaking changes with new version of TS compiler being released, more strict expression has been used in `package.json` to control its version. Not necessary anymore gulp plugin has been removed.

### Problem
The problem represents itself in the following form - while trying to debug `yarn test:projects:cra-ts` command developer might observer the fact that after this command being run once and local changes being introduced to Stardust files, **the unchanged files are used in @stardust package installed for test project**.  Cause of the problem is that `yarn add` command results in added package being implicitly cached (https://yarnpkg.com/lang/en/docs/cli/cache/). This behavior results in cached package files used with each repetition of this command (note that this primarily attributes to local debugging cases, as for CI clean container is deployed each time).

### Solution
This problem is fixed by replacing `yarn add` command on `npm install` one for test scenario.

### CODE REVIEW

**Review by hughreeling — APPROVED** [review]

File: build/gulp/tasks/test-projects.tsx [hunk 1]
```diff
@@ -108,29 +97,25 @@ export default App;
...
+    )
 
     const runInTestApp = runIn(testAppPath())
     log(`Test React project is successfully created: ${testAppPath()}`)
 
     //////// ADD STARDUST AS A DEPENDENCY ///////
     log('STEP 2. Add Stardust dependency to test project..')
 
-    await runInTestApp(`yarn add ${paths.base(stardustPackageFilename)}`)
+    await runInTestApp(`npm install add ${paths.base(stardustPackageFilename)}`)
```
Comment (levithomason) [inline build/gulp/tasks/test-projects.tsx]: typo npm install add

**Review by levithomason — APPROVED** [review]
thanks!

File: build/gulp/tasks/test-projects.tsx (hunk 1 above)
Comment (kuzhelov) [reply build/gulp/tasks/test-projects.tsx]: thank you!
