### PR TITLE
fix(whatInput): cleanup previously added event listeners

### LINKED ISSUE #2109: Memory: Window object leaks in what-input.ts
## Bug Report
We uncovered the following issues during memory investigations:
- The code in this file is referencing the global window object instead of working off of the supplied target window
- We are adding event listeners to the child window and not removing them. Refer to the addEventListener function in what-input.ts

### Version
0.40.3

### PR DESCRIPTION
**Pull request by silviuaavram**
Fixes https://github.com/microsoft/fluent-ui-react/issues/2109

Counting on `target[whatInputInitialized]` the number of Providers requesting to setup the custom-target whatInput.

To cleanup, in Provider `componentWillUnmount` we will attempt to remove listeners. If there are still Providers running (`target[whatInputInitialized] > 1`) then we will decrement that value. If it's the last one, then we perform cleanup.

Extra:
- in `whatInput.ts` I changed `useCapture` with `capture` (line 92). According to the [docs](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) that is the correct property if we pass the information inside the `options` object params.

To Do:
- add test to check cleanup is performed.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/fluent-ui-react/pull/2127)

### CODE REVIEW

File: packages/react/src/lib/whatInput.ts [hunk 1]
```diff
@@ -212,17 +214,55 @@ export const setUpWhatInput = (target: Document) => {
...
 }
 
+function cleanupWhatInput(eventTarget: Window) {
+  const options = supportsPassive ? { capture: true } : true
+
+  // @ts-ignore
+  if (eventTarget.PointerEvent) {
+    eventTarget.removeEventListener('pointerdown', setInput)
+    // @ts-ignore
+  } else if (window.MSPointerEvent) {
```
Comment (silviuaavram) [inline packages/react/src/lib/whatInput.ts:236]: still thinking why here there is `window` and not `eventTarget`.

Comment (silviuaavram) [reply packages/react/src/lib/whatInput.ts:236]: I am replacing this. @jurokapsiar @layershifter any comments?

File: packages/react/test/specs/components/Provider/Provider-test.tsx [hunk 2]
```diff
@@ -232,4 +232,58 @@ describe('Provider', () => {
...
+
+      mount(
+        <Provider id="first-provider" target={externalDocument}>
+          <Provider id="second-provider" target={externalDocument}>
+            <div />
+          </Provider>
+        </Provider>,
+      )
+
+      expect(addEventListener).toHaveBeenCalledTimes(5)
```
Comment (miroslavstastny) [inline packages/react/test/specs/components/Provider/Provider-test.tsx:260]: black magic

File: packages/react/src/lib/whatInput.ts [hunk 3]
```diff
@@ -87,14 +89,14 @@ const addListeners = (eventTarget: Window) => {
   // `pointermove`, `MSPointerMove`, `mousemove` and mouse wheel event binding
   // can only demonstrate potential, but not actual, interaction
   // and are treated separately
-  const options = supportsPassive ? { passive: true, useCapture: true } : true
+  const options = supportsPassive ? { passive: true, capture: true } : true
```
Comment (miroslavstastny) [inline packages/react/src/lib/whatInput.ts:92]: 👍

**Review by miroslavstastny — APPROVED** [review]
Approved, it would be great if @jurokapsiar could check it as well as he originally added multi-window support

File: packages/react/test/specs/components/Provider/Provider-test.tsx (hunk 2 above)
Comment (jurokapsiar) [reply packages/react/test/specs/components/Provider/Provider-test.tsx:260]: https://www.numerology.com/numerology-numbers/5

Comment (silviuaavram) [reply packages/react/test/specs/components/Provider/Provider-test.tsx:260]: ok ok will add a comment why :))))

File: packages/react/src/lib/whatInput.ts (hunk 1 above)
Comment (jurokapsiar) [reply packages/react/src/lib/whatInput.ts:236]: this is basically a platform check - saying "does this browser have MSPointerEvent?"

Comment (silviuaavram) [reply packages/react/src/lib/whatInput.ts:236]: will revert it then, but shouldn't the check above mean similarly? `eventTarget.PointerEvent`
