### PR TITLE
docs(sidebar): fix background of sidebar search input element

### LINKED ISSUE #1835: Sidebar search input does not have background
### Expected Result
image

### Actual Result
image

### Version
a8077c92b7310724fd9d8973821be5ed864edbb4

### PR DESCRIPTION
**Pull request by lucivpav**
Fixes #1835.

Now:
image

### CODE REVIEW

File: docs/src/components/Sidebar/Sidebar.tsx [hunk 1]
```diff
@@ -465,6 +465,7 @@ class Sidebar extends React.Component<any, any> {
           </a>
           <Input
             styles={topItemTheme}
+            variables={siteVars => ({ backgroundColor: siteVars.colorScheme.default.background3 })}
```
Comment (layershifter) [inline docs/src/components/Sidebar/Sidebar.tsx]:
```suggestion
            inverted
```

I was able to get the same result with `inverted` prop, #1684.

image

**Review by layershifter — APPROVED** [review]
