### PR TITLE
fix(attachment): action click

### LINKED ISSUE #1334: Attachment's action icon button onclick isn't working correctly when attachment is focused
### Steps
1. Click on the action icon in the attachment and notice that the action's onClick event is fired.
2. Focus the Attachment, then click on the action icon and notice that the attachment's onClick event gets fired. 

### Expected Result
I expect that the action's onClick event is fired whenever it is clicked on, regardless of it the Attachment is focused or not.

### Actual Result
The Attachment onClick event is fired when clicking the action icon when the attachment is focused.

attachment-onClick-bug

### PR DESCRIPTION
**Pull request by bmdalex**
### Description

This PR fixes #1334 

Steps to reproduce issue:

1. Click on the action icon in the attachment and notice that the action's onClick event is fired.
2. Focus the Attachment, then click on the action icon and notice that the attachment's onClick event gets fired.

### Fix

Add `pointerEvents: 'none'` to `getBorderFocusStyles.ts` style helper in order ignore pointer events for the pseudo elements.

### BEFORE
The Attachment onClick event is fired when clicking the action icon when the attachment is focused.

attachment-onClick-bug

### AFTER
Screen Recording 2019-06-03 at 14 43 59

### CODE REVIEW

**Review by layershifter — APPROVED** [review]

File: packages/react/src/themes/teams/getBorderFocusStyles.ts [hunk 1]
```diff
@@ -22,6 +22,7 @@ const getPseudoElementStyles = (args: BorderPseudoElementStyles): ICSSInJSStyle
     content: '""',
     position: 'absolute',
     borderStyle: 'solid',
+    pointerEvents: 'none',
```
Comment (jurokapsiar) [inline packages/react/src/themes/teams/getBorderFocusStyles.ts:25]: @kolaps33 please test this with screen readers

**Review by kolaps33 — COMMENTED** [review]
tested with VoiceOver looks ok :)
