### PR TITLE
fix(Popup): defaultOpen prop

### LINKED ISSUE #657: Popup defaultOpen is not working
### Steps
Setting defaultOpen on the Popup is not working

### Expected Result
If defaultOpen is set to true on the Popup it should be opened.

### Actual Result
The Popup is not opened.

### Version
0.15.0

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

### PR DESCRIPTION
**Pull request by mnajdova**
This PR fixes https://github.com/stardust-ui/react/issues/657 - `defaultOpen` prop on the `Popup` is not working.

### CODE REVIEW

File: src/components/Popup/Popup.tsx [hunk 1]
```diff
@@ -183,8 +183,6 @@ export default class Popup extends AutoControlledComponent<ReactProps<PopupProps
     }
   }
 
-  public state = { target: undefined, open: false }
-
```
Comment (sophieH29) [inline src/components/Popup/Popup.tsx:187]: Just to raise attention, there is an issue currently in Autocontrolled component. It doesn't allow to have both autocontrolled and non-controlled state.
Created this 1 week ago - https://github.com/stardust-ui/react/issues/610

Because it might be needed to have an initial state  explicitly set for `target`

**Review by kuzhelov — APPROVED** [review]
👍

File: src/components/Popup/Popup.tsx (hunk 1 above)
Comment (mnajdova) [reply src/components/Popup/Popup.tsx:187]: the target is also an auto-controlled prop in this case, so it is safe to be removed.
